In [1]:
import pyscf
from pyscf import grad #required for direct TDA call
import numpy
numpy.set_printoptions(precision=7, suppress=True)

In [7]:
#pyscf molecule
pyscf_mol = pyscf.gto.M(
atom='O 0 0 0;'
     'H 0 0 1.795239827225189;'
     'H 1.693194615993441 0 -0.599043184453037;',
basis='sto-3g',
unit='au'
) 

In [8]:
# PYSCF
pyscf_drv = pyscf.scf.RKS(pyscf_mol) #use scf.RHF for HF reference state
pyscf_drv.xc = "b88,lyp"
pyscf_drv.conv_tol = 1e-6
pyscf_drv.kernel()

converged SCF energy = -75.2718075857227


-75.27180758572268

In [9]:
pyscf_tda = pyscf_drv.TDA()
eigenvals, eigenvects = pyscf_tda.kernel()
pyscf_tda.analyze()
dir(pyscf_tda)

Excited State energies (eV)
[11.2454306 13.5624295 14.0921608]

** Singlet excitation energies and oscillator strengths **
Excited State   1:     11.24543 eV    110.25 nm  f=0.0027
Excited State   2:     13.56243 eV     91.42 nm  f=0.0632
Excited State   3:     14.09216 eV     87.98 nm  f=0.0000


['Gradients',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_contract_multipole',
 '_keys',
 '_scf',
 'analyze',
 'apply',
 'as_scanner',
 'check_sanity',
 'chkfile',
 'conv_tol',
 'converged',
 'dump_flags',
 'e',
 'e_tot',
 'gen_vind',
 'get_ab',
 'get_nto',
 'get_precond',
 'init_guess',
 'kernel',
 'level_shift',
 'lindep',
 'max_cycle',
 'max_memory',
 'max_space',
 'mol',
 'nroots',
 'nstates',
 'nuc_grad_method',
 'oscillator_strength',
 'post_kernel',
 'pre_kernel',
 'reset',
 'run',
 'set',
 'singlet',
 'stdout',
 'transition_dipole',
 'transition_magnetic_dipole',
 'transition_magnetic_quadrupole',
 'transition_octupole',
 'transition_quadrupo

In [10]:
eigenvals

array([0.413262 , 0.4984101, 0.5178774])

In [11]:
eigen_vect = eigenvects[0][0]
print(eigen_vect)

[[ 0.         0.       ]
 [-0.         0.       ]
 [ 0.         0.       ]
 [ 0.        -0.       ]
 [ 0.7071067  0.0003108]]


In [12]:
eigenvects

[(array([[ 0.       ,  0.       ],
         [-0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       , -0.       ],
         [ 0.7071067,  0.0003108]]),
  0),
 (array([[-0.0000911, -0.0000011],
         [ 0.0485056, -0.0001272],
         [-0.0005305, -0.1310604],
         [-0.6931594,  0.0002457],
         [ 0.       , -0.       ]]),
  0),
 (array([[-0.       , -0.       ],
         [-0.       , -0.       ],
         [-0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.0003108, -0.7071067]]),
  0)]

In [13]:
numpy.linalg.norm(eigen_vect)

0.7071067811865476

In [14]:
tda_gradient = pyscf_tda.Gradients()

In [15]:
tda_gradient.kernel(eigenvects[0])
#dir(tda_gradient.view)

PYSCF Z1, TDDFT
[[ 0.0003748  0.2008367 -0.0015344  0.1458698 -0.       ]
 [-0.0000033 -0.0000709 -0.3174125  0.0005858  0.       ]]

 div. by 4
[[ 0.0000937  0.0502092 -0.0003836  0.0364675 -0.       ]
 [-0.0000008 -0.0000177 -0.0793531  0.0001465  0.       ]]
--------- TDA gradients for state 1 ----------
         x                y                z
0 O     0.2866133450     0.0000000000     0.2013864924
1 H     0.0418173342     0.0000000000    -0.3625578919
2 H    -0.3290345187     0.0000000000     0.1607471336
----------------------------------------------


array([[ 0.2866133,  0.       ,  0.2013865],
       [ 0.0418173,  0.       , -0.3625579],
       [-0.3290345,  0.       ,  0.1607471]])