In [9]:
import pyscf
from pyscf import grad #required for direct TDA call
import numpy
numpy.set_printoptions(precision=7, suppress=True)

In [10]:
#pyscf molecule
pyscf_mol = pyscf.gto.M(
atom='O 0 0 0;'
     'H 0 0 1.795239827225189;'
     'H 1.693194615993441 0 -0.599043184453037;',
basis='sto-3g',
unit='au'
) 

In [11]:
# PYSCF
pyscf_drv = pyscf.scf.RHF(pyscf_mol)
pyscf_drv.conv_tol = 1e-6
pyscf_drv.kernel()

converged SCF energy = -74.9593192866306


-74.95931928663063

In [12]:
pyscf_tda = pyscf_drv.TDA()
eigenvals, eigenvects = pyscf_tda.kernel()

Excited State energies (eV)
[13.1548063 15.6247102 16.3848932]


In [13]:
eigenvals

array([0.4834302, 0.5741975, 0.6021337])

In [14]:
eigen_vect = eigenvects[0][0]
print(eigen_vect)

[[-0.         0.       ]
 [ 0.        -0.       ]
 [ 0.        -0.       ]
 [ 0.        -0.       ]
 [ 0.7071065  0.0006745]]


In [15]:
eigenvects

[(array([[-0.       ,  0.       ],
         [ 0.       , -0.       ],
         [ 0.       , -0.       ],
         [ 0.       , -0.       ],
         [ 0.7071065,  0.0006745]]),
  0),
 (array([[-0.       , -0.       ],
         [ 0.       , -0.       ],
         [ 0.       , -0.       ],
         [-0.       , -0.       ],
         [ 0.0006745, -0.7071065]]),
  0),
 (array([[-0.0005829, -0.000001 ],
         [ 0.0422774, -0.000075 ],
         [-0.000752 , -0.1412219],
         [-0.6915693, -0.0002368],
         [ 0.       ,  0.       ]]),
  0)]

In [16]:
numpy.linalg.norm(eigen_vect)

0.7071067811865476

0.500005001