In [1]:
import pyscf
from pyscf import grad #required for direct TDA call
import numpy
numpy.set_printoptions(precision=7, suppress=True)

In [2]:
#pyscf molecule
pyscf_mol = pyscf.gto.M(
atom='O 0 0 0;'
     'H 0 0 1.795239827225189;'
     'H 1.693194615993441 0 -0.599043184453037;',
basis='sto-3g',
unit='au'
) 

In [3]:
# PYSCF
pyscf_drv = pyscf.scf.RHF(pyscf_mol)
pyscf_drv.conv_tol = 1e-6
pyscf_drv.kernel()

converged SCF energy = -74.9593192866306


-74.95931928663063

In [4]:
pyscf_tda = pyscf_drv.TDA()
eigenvals, eigenvects = pyscf_tda.kernel()
pyscf_tda.analyze()
dir(pyscf_tda)

Excited State energies (eV)
[13.1548063 15.6247102 16.3848932]

** Singlet excitation energies and oscillator strengths **
Excited State   1:     13.15481 eV     94.25 nm  f=0.0039
Excited State   2:     15.62471 eV     79.35 nm  f=0.0000
Excited State   3:     16.38489 eV     75.67 nm  f=0.0665


['Gradients',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_contract_multipole',
 '_keys',
 '_scf',
 'analyze',
 'apply',
 'as_scanner',
 'check_sanity',
 'chkfile',
 'conv_tol',
 'converged',
 'dump_flags',
 'e',
 'e_tot',
 'gen_vind',
 'get_ab',
 'get_nto',
 'get_precond',
 'init_guess',
 'kernel',
 'level_shift',
 'lindep',
 'max_cycle',
 'max_memory',
 'max_space',
 'mol',
 'nroots',
 'nstates',
 'nuc_grad_method',
 'oscillator_strength',
 'post_kernel',
 'pre_kernel',
 'reset',
 'run',
 'set',
 'singlet',
 'stdout',
 'transition_dipole',
 'transition_magnetic_dipole',
 'transition_magnetic_quadrupole',
 'transition_octupole',
 'transition_quadrupo

In [5]:
eigenvals

array([0.4834302, 0.5741975, 0.6021337])

In [6]:
eigen_vect = eigenvects[0][0]
print(eigen_vect)

[[-0.        -0.       ]
 [ 0.         0.       ]
 [-0.        -0.       ]
 [-0.        -0.       ]
 [ 0.7071065  0.0006745]]


In [7]:
eigenvects

[(array([[-0.       , -0.       ],
         [ 0.       ,  0.       ],
         [-0.       , -0.       ],
         [-0.       , -0.       ],
         [ 0.7071065,  0.0006745]]),
  0),
 (array([[ 0.       ,  0.       ],
         [-0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.0006745, -0.7071065]]),
  0),
 (array([[ 0.0005829,  0.000001 ],
         [-0.0422774,  0.000075 ],
         [ 0.000752 ,  0.1412219],
         [ 0.6915693,  0.0002368],
         [ 0.       ,  0.       ]]),
  0)]

In [8]:
numpy.linalg.norm(eigen_vect)

0.7071067811865476

In [9]:
tda_gradient = pyscf_tda.Gradients()

In [10]:
tda_gradient.kernel(eigenvects[0])
#dir(tda_gradient.view)


PYSCF Z1:
(5, 2)
[[ 0.0007725 -0.000002 ]
 [ 0.120848  -0.0000164]
 [-0.0010734 -0.3172186]
 [ 0.0731763  0.0005631]
 [-0.         0.       ]]

PYSCF Z1, AO:
(7, 7)
[[ 0.0027181 -0.0084424 -0.0081517  0.        -0.0057091 -0.005263
  -0.0053286]
 [-0.0182045  0.0565431  0.0545748 -0.         0.0382667  0.0352756
   0.035661 ]
 [-0.0116846  0.0362463  0.0993144  0.        -0.0658382 -0.0588292
   0.1046228]
 [-0.         0.         0.         0.        -0.        -0.
   0.       ]
 [-0.0082737  0.0257629 -0.0660854 -0.         0.1452015  0.1312182
  -0.0993503]
 [ 0.0161903 -0.0503534  0.0444007  0.        -0.1647231 -0.1491546
   0.0864466]
 [ 0.0161682 -0.0501517 -0.1414464 -0.         0.0967593  0.086502
  -0.1498838]]

(7, 7)
[[ 0.3281563  0.0667625  0.0013945 -0.         0.0009855  0.0148685
   0.0148529]
 [ 0.0667625  0.1316714 -0.0270638 -0.        -0.018991   0.0471336
   0.0470236]
 [ 0.0013945 -0.0270638  0.1059069 -0.         0.0368502 -0.0036022
   0.0193441]
 [-0.        -

array([[ 0.2519584,  0.       ,  0.176439 ],
       [ 0.0438383, -0.       , -0.3275707],
       [-0.2957967, -0.       ,  0.1511316]])