In [1]:
import pyscf
from pyscf import grad #required for direct TDA call
import numpy
#numpy.set_printoptions(precision=10, suppress=True)

In [2]:
#pyscf molecule
pyscf_mol = pyscf.gto.M(
atom='O 0 0 0;'
     'H 0 0 1.795239827225189;'
     'H 1.693194615993441 0 -0.599043184453037;',
basis='sto-3g',
unit='au'
) 

In [3]:
# PYSCF
pyscf_drv = pyscf.scf.RHF(pyscf_mol)
pyscf_drv.conv_tol = 1e-6
pyscf_drv.kernel()

converged SCF energy = -74.9593192866306


-74.95931928663065

In [4]:
pyscf_tda = pyscf_drv.TDA()
eigenvals, eigenvects = pyscf_tda.kernel()

Excited State energies (eV)
[13.15480634 15.62471018 16.38489321]


In [5]:
eigenvals

array([0.48343022, 0.57419751, 0.60213372])

In [6]:
eigen_vect = eigenvects[0][0]
print(eigen_vect)

[[ 2.46743645e-19 -3.93861621e-19]
 [-2.72521562e-17  1.28501399e-17]
 [-3.45395780e-16  4.23728753e-17]
 [-3.88613216e-16  4.26866865e-17]
 [ 7.07106459e-01  6.74518283e-04]]


In [7]:
eigenvects

[(array([[ 2.46743645e-19, -3.93861621e-19],
         [-2.72521562e-17,  1.28501399e-17],
         [-3.45395780e-16,  4.23728753e-17],
         [-3.88613216e-16,  4.26866865e-17],
         [ 7.07106459e-01,  6.74518283e-04]]),
  0),
 (array([[-1.09673861e-17, -6.47996383e-19],
         [ 7.83477388e-16, -1.41446253e-17],
         [ 3.68073094e-17, -2.88943199e-15],
         [-1.25607397e-14, -4.55953251e-16],
         [-6.74518283e-04,  7.07106459e-01]]),
  0),
 (array([[ 5.82919595e-04,  1.03920805e-06],
         [-4.22773951e-02,  7.50442872e-05],
         [ 7.51993122e-04,  1.41221898e-01],
         [ 6.91569252e-01,  2.36827045e-04],
         [ 3.58077868e-16,  1.31102720e-14]]),
  0)]

In [8]:
numpy.linalg.norm(eigen_vect)

0.7071067811865476

In [9]:
0.70711**2+0.00067**2

0.500005001