In [1]:
import veloxchem as vlx

In [2]:
class MockTask:
    def __init__(self, mol, basis, comm, ostream):

        self.molecule = mol
        self.ao_basis = basis
        self.mpi_comm = comm
        self.ostream = ostream

In [85]:
import adcc
from mpi4py import MPI
import sys
import numpy
numpy.set_printoptions(precision=4, suppress=True)

In [4]:
# Input settings
molecule_string = """
    O 0 0 0
    H 0 0 1.795239827225189
    H 1.693194615993441 0 -0.599043184453037"""

#molecule_string = """
#    H 0 0 0
#    H 0 0 1.795239827225189
#    """

basis_set_label = 'STO-3G'
scf_settings = {'conv_thresh': 1.0e-6}
method_settings = {} #{'xcfun': 'b3lyp', 'grid_level': 4}
rsp_settings = {'conv_thresh': 1.0e-4, 'nstates': 2}

In [5]:
# Communicator and output stream
comm = MPI.COMM_WORLD
ostream = vlx.OutputStream(sys.stdout)

In [6]:
# Molecule and basis set
molecule = vlx.Molecule.read_str(molecule_string, units='au')
basis = vlx.MolecularBasis.read(molecule, basis_set_label)

ostream.print_block(molecule.get_string())
ostream.print_block(basis.get_string('Atomic Basis', molecule))
ostream.flush()

                                              Molecular Geometry (Angstroms)                                              
                                                                                                                          
                          Atom         Coordinate X          Coordinate Y          Coordinate Z                           
                                                                                                                          
                           O           0.000000000000        0.000000000000        0.000000000000                         
                           H           0.000000000000        0.000000000000        0.950000004704                         
                           H           0.896000004436        0.000000000000       -0.317000001569                         
                                                                                                                          
                

In [7]:
# SCF
task = MockTask(molecule, basis, comm, ostream)
scfdrv = vlx.ScfRestrictedDriver(comm, ostream)
scfdrv.update_settings(scf_settings, method_settings)
scfdrv.compute(molecule, basis)
scfdrv.task = task

                                                                                                                          
                                            Self Consistent Field Driver Setup                                            
                                                                                                                          
                   Wave Function Model             : Spin-Restricted Hartree-Fock                                         
                   Initial Guess Model             : Superposition of Atomic Densities                                    
                   Convergence Accelerator         : Two Level Direct Inversion of Iterative Subspace                     
                   Max. Number of Iterations       : 50                                                                   
                   Max. Number of Error Vectors    : 10                                                                   
                

In [8]:
# SCF first-order properties
scf_prop = vlx.ScfFirstOrderProperties(comm, ostream)
scf_prop.compute(molecule, basis, scfdrv.scf_tensors)
scf_prop.print_properties(molecule)

                                                                                                                          
                                                Ground-State Dipole Moment                                                
                                               ----------------------------                                               
                                                                                                                          
                                   X   :         0.546314 a.u.         1.388593 Debye                                     
                                   Y   :        -0.000000 a.u.        -0.000000 Debye                                     
                                   Z   :         0.386302 a.u.         0.981881 Debye                                     
                                 Total :         0.669095 a.u.         1.700671 Debye                                     
                

In [9]:
# Linear Response
#lr_eig_drv = vlx.LinearResponseEigenSolver(comm, ostream)
#lr_eig_drv.update_settings(rsp_settings, method_settings)
#lr_results = lr_eig_drv.compute(molecule, basis, scfdrv.scf_tensors)
#lr_eig_drv.ostream.flush()

In [10]:
# TDHF/TDA, i.e. CIS
tda_drv = vlx.TDAExciDriver(comm, ostream)
tda_drv.update_settings(rsp_settings, method_settings)
tda_results = tda_drv.compute(molecule, basis, scfdrv.scf_tensors)
tda_drv.ostream.flush()

                                                                                                                          
                                                     TDA Driver Setup                                                     
                                                                                                                          
                               Number of States                : 3                                                        
                               Max. Number of Iterations       : 150                                                      
                               Convergence Threshold           : 1.0e-04                                                  
                               ERI Screening Scheme            : Cauchy Schwarz + Density                                 
                               ERI Screening Threshold         : 1.0e-15                                                  
                

In [11]:
# Get MO coefficients, eigenvalues and eigenvectors

nocc = molecule.number_of_alpha_electrons()
mo = scfdrv.scf_tensors['C'] # MO coefficients
mo_occ = mo[:, :nocc]        # occupied
mo_vir = mo[:, nocc:]        # virtual

nocc = mo_occ.shape[1]
nvir = mo_vir.shape[1]

#eig_vals = lr_results["eigenvalues"]
#eig_vecs = lr_results["eigenvectors"]

#eig_vec = eig_vecs[:, 0].copy() # first eigenvector
#print(eig_vec)
print("mo_occ:")
print(mo_occ)
print()
print("mo_vir:")
print(mo_vir)

mo_occ:
[[ 0.9941004 -0.2328975 -0.0000651  0.100218  -0.       ]
 [ 0.0267754  0.831866   0.0003549 -0.5233254  0.       ]
 [-0.0060845  0.1602965 -0.4415424  0.2690375 -0.       ]
 [-0.0060786  0.1601297  0.4415634  0.2692781 -0.       ]
 [-0.        -0.        -0.        -0.        -1.       ]
 [ 0.0024519  0.0731199 -0.4902285  0.4582282 -0.       ]
 [ 0.0034627  0.1032171  0.3463593  0.6483629 -0.       ]]

mo_vir:
[[-0.1356068 -0.0002233]
 [ 0.9082267  0.0016893]
 [-0.8061613 -0.8437321]
 [-0.8082193  0.8410846]
 [ 0.         0.       ]
 [ 0.4112391  0.8244283]
 [ 0.5840568 -0.5814893]]


In [69]:
print(scfdrv.scf_tensors.keys())
# Transform the Fock matrix from AO to MO basis
fock = scfdrv.scf_tensors['F'][0]
ovlp = scfdrv.scf_tensors['S']
print(numpy.matmul(mo.T, numpy.matmul(ovlp, mo)))
print(numpy.matmul(mo.T, numpy.matmul(fock, mo)))

dict_keys(['C', 'E', 'S', 'D', 'F'])
[[ 1.  0. -0. -0.  0. -0.  0.]
 [ 0.  1. -0.  0.  0. -0. -0.]
 [-0. -0.  1. -0.  0. -0.  0.]
 [-0.  0. -0.  1.  0. -0.  0.]
 [ 0.  0.  0.  0.  1. -0. -0.]
 [-0. -0. -0. -0. -0.  1. -0.]
 [ 0. -0.  0.  0. -0. -0.  1.]]
[[-20.2333974  -0.         -0.         -0.         -0.         -0.
   -0.       ]
 [ -0.         -1.2657146  -0.         -0.         -0.          0.0000002
    0.       ]
 [ -0.         -0.         -0.6292671  -0.         -0.         -0.
    0.0000001]
 [ -0.         -0.         -0.         -0.441668   -0.          0.
    0.       ]
 [ -0.         -0.         -0.         -0.         -0.3876451  -0.
    0.       ]
 [ -0.          0.0000002  -0.          0.         -0.          0.6028394
    0.       ]
 [ -0.          0.          0.0000001   0.          0.          0.
    0.7659184]]


In [13]:
# Convert the first eigenvector to matrix form
#eig_vec_as_mat = vlx.LinearResponseEigenSolver.lrvec2mat(eig_vec, nocc, nocc + nvir)

In [14]:
tda_eig_vals = tda_results["eigenvalues"]
tda_eig_vecs = tda_results["eigenvectors"]
tda_size = tda_eig_vecs[:,0].shape
tda_eig_vec=tda_eig_vecs[:,0].copy()
tda_eig_vec_as_mat = tda_eig_vec.reshape(nocc, nvir) #/ numpy.sqrt(2.0)

In [15]:
print(tda_eig_vec)

[ 0.        -0.         0.         0.         0.        -0.
  0.        -0.         0.9999995 -0.0009539]


In [16]:
#tda_eig_vec_as_mat = vlx.LinearResponseEigenSolver.lrvec2mat(tda_eig_vec, nocc, nocc + nvir)

In [17]:
print(tda_eig_vec_as_mat)

[[ 0.        -0.       ]
 [ 0.         0.       ]
 [ 0.        -0.       ]
 [ 0.        -0.       ]
 [ 0.9999995 -0.0009539]]


In [18]:
adc1 = adcc.run_adc(scfdrv, method='adc1', n_singlets=3, conv_tol=1e-4)

Starting adc1 singlet Jacobi-Davidson ...
Niter n_ss  max_residual  time  Ritz values
  1     6     0.0028135   71ms  [0.4834361 0.5742004 0.6052005]
  2    10    2.6249e-29   63ms  [0.4834361 0.5742004 0.602137 ]
=== Converged ===
    Number of matrix applies:    10
    Total solver time:           138.367ms


In [19]:
adc1_eig_vec = adc1.excitation_vector[0]["s"].to_ndarray()
adc1_eig_vals = adc1.excitation_energy
adc1.state_dipole_moment

array([[-0.2107821, -0.       , -0.1423893],
       [ 0.0418873, -0.       ,  0.0233941],
       [-0.3315493,  0.       , -0.2288044]])

In [20]:
print(adc1_eig_vec)
print(adc1_eig_vals)
print(adc1.describe())

[[ 0.        -0.         0.         0.       ]
 [-0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.       ]
 [-0.7071065  0.0006745  0.         0.       ]
 [ 0.         0.         0.        -0.       ]
 [ 0.         0.        -0.         0.       ]
 [ 0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.       ]
 [ 0.         0.        -0.7071065  0.0006745]]
[0.4834361 0.5742004 0.602137 ]
+----------------------------------------------------+
| adc1                          singlet ,  converged |
+----------------------------------------------------+
|  #        excitation energy     osc str    |v1|^2  |
|          (au)           (eV)                       |
|  0     0.4834361      13.15497   0.0038         1  |
|  1     0.5742004      15.62479   0.0000         1  |
|  2      0.602137      16.38498   0.0546         1  |
+----------------------------------------------------+



In [21]:
print(tda_eig_vecs[:,0])
print(tda_eig_vals)

[ 0.        -0.         0.         0.         0.        -0.
  0.        -0.         0.9999995 -0.0009539]
[0.4834361 0.5742005 0.6021371]


In [22]:
numpy.linalg.norm(adc1_eig_vec)

1.0

In [23]:
0.9999995/numpy.sqrt(2.0)

0.7071064276331569

In [24]:
0.0009539/numpy.sqrt(2.0)

0.0006745091585738476

In [25]:
print(adc1_eig_vec.shape)
print(adc1_eig_vec)
print()
print(tda_eig_vec_as_mat.shape)
print(tda_eig_vec_as_mat/numpy.sqrt(2))

(10, 4)
[[ 0.        -0.         0.         0.       ]
 [-0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.       ]
 [-0.7071065  0.0006745  0.         0.       ]
 [ 0.         0.         0.        -0.       ]
 [ 0.         0.        -0.         0.       ]
 [ 0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.       ]
 [ 0.         0.        -0.7071065  0.0006745]]

(5, 2)
[[ 0.        -0.       ]
 [ 0.         0.       ]
 [ 0.        -0.       ]
 [ 0.        -0.       ]
 [ 0.7071065 -0.0006745]]


In [26]:
vlx_dm_oo = -numpy.einsum('ia,ja->ij', tda_eig_vec_as_mat, tda_eig_vec_as_mat)
vlx_dm_vv = numpy.einsum('ia,ib->ab', tda_eig_vec_as_mat, tda_eig_vec_as_mat)
vlx_DM_ovov = -numpy.einsum('ib,ja->iajb', tda_eig_vec_as_mat, tda_eig_vec_as_mat)

print(vlx_dm_oo)

[[-0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -1.]]


In [98]:
adcc_dm_oo = -numpy.einsum('ia,ja->ij', adc1_eig_vec, adc1_eig_vec)
adcc_dm_vv = numpy.einsum('ia,ib->ab', adc1_eig_vec, adc1_eig_vec)
adcc_DM_ovov = -numpy.einsum('ib,ja->iajb', adc1_eig_vec, adc1_eig_vec)

#print(adcc_dm_oo)

foo = adc1.reference_state.fock("o1o1").to_ndarray()
fvv = adc1.reference_state.fock("v1v1").to_ndarray()
ovov = adc1.reference_state.eri("o1v1o1v1").to_ndarray()

adcc_excitation_energy = (numpy.einsum('ij,ij->',adcc_dm_oo,foo)
                     + numpy.einsum('ab,ab->', adcc_dm_vv, fvv)
                     + numpy.einsum('iajb,iajb->', adcc_DM_ovov, ovov)
                    )

In [99]:
print(adcc_excitation_energy)

0.4834361086240112


$E = \frac{1}{4} \sum_{pqrs} \Gamma_{pqrs} \langle pq || rs \rangle$

$\langle ia || jb \rangle = - \langle ai || jb \rangle = - \langle ia || bj \rangle = \langle ai || bj \rangle$

analogous symmetry for $\boldsymbol{\Gamma}$

In [29]:
vlx_excitation_energy = (1.0*numpy.einsum('ij,ij->', vlx_dm_oo,foo[:nocc,:nocc])
                        +1.0*numpy.einsum('ab,ab->', vlx_dm_vv, fvv[:nvir,:nvir])
                        +1.0*(
                        +1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc, :nvir, :nocc, :nvir])##aaaa
                        #+0.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc, :nvir, :nocc, nvir:])# zero block
                        #+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc, :nvir, nocc:, :nvir])# zero block
                        #+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc, :nvir, nocc:, nvir:])# zero block
                        #+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc, nvir:, :nocc, :nvir])# zero block
                        #+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc, nvir:, :nocc, nvir:])# zero block
                        +1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc, nvir:, nocc:, :nvir])##bbbb
                        #+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc, nvir:, nocc:, nvir:])# zero block
                        #+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[nocc:, :nvir, :nocc, :nvir])# zero block
                        #+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[nocc:, :nvir, :nocc, nvir:])##abba
                        #+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[nocc:, :nvir, nocc:, :nvir])# zero block
                        #+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[nocc:, nvir:, :nocc, :nvir])# zero block
                        #+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[nocc:, nvir:, :nocc, nvir:])# zero block
                        #+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[nocc:, nvir:, nocc:, :nvir])# zero block
                        #+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[nocc:, nvir:, nocc:, nvir:])##baab
                        ))
print("vlx energy =", vlx_excitation_energy)

vlx energy = 0.4834361086240113


In [30]:
print(vlx_excitation_energy)

0.4834361086240113


In [31]:
adcc_excitation_energy = (1.0*numpy.einsum('ij,ij->', vlx_dm_oo,foo[:nocc,:nocc])
                        +1.0*numpy.einsum('ab,ab->', vlx_dm_vv, fvv[:nvir,:nvir])
                        +2.0*numpy.einsum('iajb,iajb->', adcc_DM_ovov[:nocc, :nvir, :nocc, :nvir], ovov[:nocc, :nvir, :nocc, :nvir])
                        +2.0*numpy.einsum('iajb,iajb->', adcc_DM_ovov[:nocc, :nvir, :nocc, :nvir], ovov[:nocc, nvir:, nocc:, :nvir])
    )
print(adcc_excitation_energy)

0.48343610862266045


In [32]:
print(ovov.shape)
#print(ovov)

(10, 4, 10, 4)


In [33]:
#print(vlx_DM_ovov)
#print()
print(vlx_DM_ovov.shape)
#print(adcc_DM_ovov)

(5, 2, 5, 2)


In [34]:
# Making the Vlx 2PDM twice the size with the other spin blocks
# and assign the corresponding values to it by comparing to the adcc matrix
# afterwards divide by two to yield the same numbers
##vlx_DM_ovov_full = numpy.zeros((2*nocc, 2*nvir, 2*nocc, 2*nvir))
#vlx_DM_ovov_full[:nocc, :nvir, :nocc, :nvir] = vlx_DM_ovov
##vlx_DM_ovov_full[0, 0, 0, 0] = vlx_DM_ovov_full[0, 3, 1, 0] = vlx_DM_ovov_full[1,0,0,3] = vlx_DM_ovov_full[1,3,1,3] = vlx_DM_ovov[0,0,0,0]
##vlx_DM_ovov_full[0, 0, 0, 2] = vlx_DM_ovov_full[0, 2, 0, 0] = vlx_DM_ovov_full[0,3,1,2] = vlx_DM_ovov_full[0,5,1,0] = vlx_DM_ovov[0,2,0,0]
##vlx_DM_ovov_full[1, 0, 0, 5] = vlx_DM_ovov_full[1, 2, 0, 3] = vlx_DM_ovov_full[1,3,1,5] = vlx_DM_ovov_full[1,5,1,3] = vlx_DM_ovov[0,2,0,0]
##vlx_DM_ovov_full[0, 2, 0, 2] = vlx_DM_ovov_full[0, 5, 1, 2] = vlx_DM_ovov_full[1,2,0,5] = vlx_DM_ovov_full[1,5,1,5] = vlx_DM_ovov[0,2,0,2]

### matrix elements were twice as large
##vlx_DM_ovov_full *= 0.5
# norm of the difference between the two density matrices does not seem to vanish entirely...
##print("norm of the difference of the 2PDMs = ", numpy.linalg.norm(adcc_DM_ovov - vlx_DM_ovov_full))
#print(vlx_DM_ovov_full)
##vlx_excitation_energy = (1.0*numpy.einsum('ij,ij->', vlx_dm_oo,foo[:nocc,:nocc])
##                        #(1.0*numpy.einsum('ij,ij->', adcc_dm_oo,foo)
##                        #+1.0*numpy.einsum('ij,ij->', adcc_dm_vv,fvv)
##                        +1.0*numpy.einsum('ab,ab->', vlx_dm_vv, fvv[:nvir,:nvir])
##                        +1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov_full, ovov)
##                        )
##print("vlx exc. energy =", vlx_excitation_energy)
#print("adcc - vlx =", adcc_excitation_energy - vlx_excitation_energy)

In [35]:
print(adcc_DM_ovov.shape)
print()
#print(adcc_DM_ovov)
print()
#print(adcc_DM_ovov - vlx_DM_ovov_full) # here everything appears to be zero

(10, 4, 10, 4)




In [36]:
# Transform the one-particle density matrices from MO to AO basis
vlx_dm_oo_in_ao = numpy.matmul(mo_occ, numpy.matmul(vlx_dm_oo, mo_occ.T))
adcc_dm_oo_in_ao = 2.0*numpy.matmul(mo_occ, numpy.matmul(adcc_dm_oo[:nocc,:nocc], mo_occ.T))

vlx_dm_vv_in_ao = numpy.matmul(mo_vir, numpy.matmul(vlx_dm_vv, mo_vir.T))
adcc_dm_vv_in_ao = 2.0*numpy.matmul(mo_vir, numpy.matmul(adcc_dm_vv[:nvir,:nvir], mo_vir.T))

vlx_dm_ao = vlx_dm_oo_in_ao + vlx_dm_vv_in_ao
adcc_dm_ao = adcc_dm_oo_in_ao + adcc_dm_vv_in_ao

print("VLX")
print(vlx_dm_ao)
print("\nADCC")
print(adcc_dm_ao)

contract_fock_mo = (1.0*numpy.einsum('ij,ij->', vlx_dm_oo, foo[:nocc,:nocc])
                    +1.0*numpy.einsum('ab,ab->', vlx_dm_vv, fvv[:nvir,:nvir]))

contract_fock_ao = numpy.einsum('mn,mn->', vlx_dm_ao, fock)

print("contract_fock_ao =", contract_fock_ao)
print("contract_fock_mo =", contract_fock_mo)

VLX
[[ 0.0183891 -0.1231612  0.1092115  0.1097085  0.        -0.05566
  -0.0792771]
 [-0.1231612  0.824872  -0.7314442 -0.734773  -0.         0.372783
   0.5309583]
 [ 0.1092115 -0.7314442  0.6485984  0.6515501  0.        -0.3305604
  -0.4708202]
 [ 0.1097085 -0.734773   0.6515501  0.6545153  0.        -0.3320647
  -0.4729629]
 [ 0.        -0.         0.         0.        -1.         0.
  -0.       ]
 [-0.05566    0.372783  -0.3305604 -0.3320647  0.         0.1684712
   0.2399551]
 [-0.0792771  0.5309583 -0.4708202 -0.4729629 -0.         0.2399551
   0.3417703]]

ADCC
[[ 0.0183891 -0.1231612  0.1092115  0.1097085 -0.        -0.05566
  -0.0792771]
 [-0.1231612  0.824872  -0.7314442 -0.734773   0.         0.372783
   0.5309583]
 [ 0.1092115 -0.7314442  0.6485984  0.6515501 -0.        -0.3305604
  -0.4708202]
 [ 0.1097085 -0.734773   0.6515501  0.6545153 -0.        -0.3320647
  -0.4729629]
 [-0.         0.        -0.        -0.        -1.        -0.
  -0.       ]
 [-0.05566    0.372783  -

In [37]:
# Calculate the total density (including HF part)
# and calculated the unrelaxed excited-state dipole moment

# dipole integrals
dipole_drv = vlx.ElectricDipoleIntegralsDriver(comm)
dipole_mats = dipole_drv.compute(molecule, basis)
dipole_ints = (dipole_mats.x_to_numpy(),
              dipole_mats.y_to_numpy(),
              dipole_mats.z_to_numpy())

# electronic contribution
total_density = 2*scfdrv.scf_tensors['D'][0] + vlx_dm_ao
adcc_total_density = 2*scfdrv.scf_tensors['D'][0] + adcc_dm_ao
electronic_dipole = -1.0 * numpy.array(
    [numpy.sum(dipole_ints[d] * total_density) for d in range(3)])
adcc_electronic_dipole = -1.0 * numpy.array(
    [numpy.sum(dipole_ints[d] * adcc_total_density) for d in range(3)])

# nuclear contribution
coords = molecule.get_coordinates()
nuclear_charges = molecule.elem_ids_to_numpy()
nuclear_dipole = numpy.sum(coords.T * nuclear_charges, axis=1)

dipole_moment = (nuclear_dipole + electronic_dipole)
adcc_dipole_moment = (nuclear_dipole + adcc_electronic_dipole)

print("dipole moment [au] =", dipole_moment)
print()
print("adcc dm dipole moment [au] =", adcc_dipole_moment)
print()
print("ADC(1) dipole moment for water in Q-Chem:")
print("Dip. moment [a.u.]:  [0.221200,  -0.00000,   0.151505]")
print()
print("ADC(1) dipole moment from adcc:")
print(adc1.state_dipole_moment)

dipole moment [au] = [-0.2107821 -0.        -0.1423893]

adcc dm dipole moment [au] = [-0.2107821 -0.        -0.1423893]

ADC(1) dipole moment for water in Q-Chem:
Dip. moment [a.u.]:  [0.221200,  -0.00000,   0.151505]

ADC(1) dipole moment from adcc:
[[-0.2107821 -0.        -0.1423893]
 [ 0.0418873 -0.         0.0233941]
 [-0.3315493  0.        -0.2288044]]


In [88]:
# Transform the excitation vectors from MO to AO basis
tda_eig_vec_ao = numpy.matmul(mo_occ, numpy.matmul(tda_eig_vec_as_mat, mo_vir.T))
print(tda_eig_vec_ao)

[[-0.      0.     -0.     -0.      0.      0.      0.    ]
 [ 0.     -0.      0.      0.     -0.     -0.     -0.    ]
 [-0.      0.     -0.     -0.      0.      0.      0.    ]
 [-0.      0.     -0.     -0.      0.      0.      0.    ]
 [ 0.1356 -0.9082  0.8054  0.809  -0.     -0.4105 -0.5846]
 [-0.      0.     -0.     -0.      0.      0.      0.    ]
 [ 0.     -0.      0.     -0.     -0.     -0.      0.    ]]


In [43]:
#dir(scfdrv)

In [89]:
# Get the ERI tensor in AO basis (chemists' notation)

nao = mo.shape[0]

pqrs = numpy.zeros((nao, nao, nao, nao))
eri_drv = vlx.ElectronRepulsionIntegralsDriver(comm)
eri_drv.compute_in_mem(molecule, basis, pqrs)
#print("(pq|rs) =")
#print(pqrs)


\begin{align}
\begin{split}
    - \sum_{\sigma \sigma'} \sum_{ijab} x_{i_{\sigma} b_{\sigma}} x_{j_{\sigma'} a_{\sigma'}}
        \langle i_{\sigma} a_{\sigma'} || j_{\sigma'} b_{\sigma} \rangle
    &= - \sum_{ijab} x_{ib} x_{ja} [ 2 (ij|ab) - 4 (ib|aj) ] \\
    &= + \sum_{ijab} x_{ib} x_{ja} [ 4 (ib|aj) - 2 (ij|ab)  ] \\
    &= \sum_{ijab} x_{ib} x_{ja} \sum_{\mu \nu \theta \varphi}
        C_{\mu i} C_{\nu b} C_{\theta a} C_{\varphi j}  [ 4 (\mu \nu | \theta \varphi)
        - 2 (\mu \varphi | \theta \nu) ] \\
    &= \sum_{\mu \nu \theta \varphi} [ 4 (\mu \nu | \theta \varphi)
        - 2 (\mu \varphi | \theta \nu) ]
        \sum_{ib} C_{\mu i} x_{ib} C_{\nu b} \sum_{ja} C_{\varphi j} x_{ja} C_{\theta a} \\
    &= \sum_{\mu \nu \theta \varphi} x_{\mu \nu} x_{\varphi \theta} [ 4 (\mu \nu | \theta \varphi)
        - 2 (\mu \varphi | \theta \nu) ]       \\
    &= \sum_{\mu \nu} x_{\mu \nu} \sum_{\theta \varphi} x_{\varphi \theta} [ 4 (\mu \nu | \theta \varphi)
        - 2 (\mu \varphi | \theta \nu) ]
\end{split}
\end{align}

In [90]:
# Contraction of electron repulsion integrals in AO basis
# First reference value in MO
eri_contract_mo_adcc = numpy.einsum('iajb,iajb->', adcc_DM_ovov, ovov)
print("Contraction in MO adcc:", eri_contract_mo_adcc)

eri_contract_mo_vlx = (+1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc, :nvir, :nocc, :nvir])##aaaa
                        +1.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc, nvir:, nocc:, :nvir]))##bbbb
print("Contraction in MO vlx: ", eri_contract_mo_vlx)

# Now contract everything in AO
eri_contract_ao = (0.5*numpy.einsum('mn,mn->', tda_eig_vec_ao, numpy.einsum('pt,mntp->mn', tda_eig_vec_ao, 4*pqrs)
                                   - numpy.einsum('pt,mptn->mn', tda_eig_vec_ao, 2*pqrs))
                    )
print("Contraction in AO:     ", eri_contract_ao)

Contraction in MO adcc: -0.5070484896790678
Contraction in MO vlx:  -0.5070484896777168
Contraction in AO:      -0.5070484896777169


In [48]:
mo.shape
print(nocc + nvir)

7


## Orbital response, right hand side

### 1. Contributions from the 1PDMs
\begin{equation}
F^\gamma_{ia}=\sum_{\theta,\varphi}C^\alpha_{\varphi i}C^\alpha_{\theta a}\sum_{\mu,\nu,\sigma}\gamma^\sigma_{\mu\nu}(\mu\nu|\theta \varphi)-\sum_{\theta,\varphi}C^\alpha_{\varphi i}C^\alpha_{\theta a}\sum_{\mu,\nu}\gamma^{\alpha}_{\mu\nu}(\mu\varphi|\theta\nu)\\
=\sum_{\theta,\varphi,\sigma}C^\alpha_{\varphi i}C^\alpha_{\theta a}F^{1,\sigma}_{\varphi\theta}-\sum_{\theta,\varphi}C^\alpha_{\varphi i}C^\alpha_{\theta a}F^{2,\alpha}_{\varphi\theta}\\
=\sum_{\theta,\varphi}C^\alpha_{\varphi i}C^\alpha_{\theta a}F_{\varphi\theta}
\end{equation}

In [66]:
F1_vlx = numpy.einsum('mn,mntp->pt', vlx_dm_ao, pqrs)
F2_vlx = numpy.einsum('mn,mptn->pt', vlx_dm_ao, pqrs)
F_1pdm_vlx = F1_vlx - 0.5*F2_vlx
vlx_1pdm_rhs = numpy.einsum('pi,pa->ia', mo_occ, numpy.einsum('ta,pt->pa', mo_vir, F_1pdm_vlx))
print(vlx_1pdm_rhs)

[[ 0.018333  -0.0000249]
 [-0.0827309 -0.0000336]
 [-0.0004581  0.1069934]
 [-0.0907946  0.0001547]
 [ 0.        -0.       ]]


In [56]:
ooov = adc1.reference_state.eri("o1o1o1v1").to_ndarray()
ovvv = adc1.reference_state.eri("o1v1v1v1").to_ndarray()
adcc_1pdm_rhs = ( -numpy.einsum('jk,ikja->ia', adcc_dm_oo, ooov, optimize=True) 
                 -numpy.einsum('bc,icba->ia', adcc_dm_vv, ovvv, optimize=True)
                )
print(adcc_1pdm_rhs)

[[ 0.018333  -0.0000249 -0.        -0.       ]
 [-0.0827309 -0.0000336 -0.        -0.       ]
 [-0.0004581  0.1069934 -0.        -0.       ]
 [-0.0907946  0.0001547 -0.        -0.       ]
 [-0.        -0.        -0.        -0.       ]
 [-0.        -0.         0.018333  -0.0000249]
 [-0.        -0.        -0.0827309 -0.0000336]
 [-0.        -0.        -0.0004581  0.1069934]
 [-0.        -0.        -0.0907946  0.0001547]
 [-0.        -0.        -0.        -0.       ]]


\begin{equation}
F^\Gamma_{ia}=\sum_{\mu,\rho}C^\alpha_{\mu a}C^\alpha_{\rho i}\left[\sum_{\tau,\varphi}S_{\rho\tau}x^\alpha_{\tau\varphi}\sum_{\nu,\theta}x^\alpha_{\theta\nu}(\mu\nu|\theta\varphi)-\sum_{\tau,\nu}S_{\rho\tau}x^\alpha_{\tau\nu}\sum_{\theta,\varphi,\sigma} x^\sigma_{\theta\varphi}(\mu\nu|\theta\varphi)\right]-\sum_{\mu,\rho}C^\alpha_{\rho i}C^\alpha_{\mu a}\left[\sum_{\tau,\varphi}S_{\mu\tau}x^\alpha_{\tau\varphi}\sum_{\nu,\theta}x^\alpha_{\theta\nu}(\rho\nu|\theta\varphi)-\sum_{\tau,\nu} S_{\mu\tau}x^\alpha_{\tau\nu}\sum_{\theta,\varphi,\sigma}x^\sigma_{\theta\varphi}(\rho\nu|\theta\varphi) \right]
\end{equation}

In [100]:
FG1_vlx =( numpy.einsum('rz,zm->rm', ovlp,
                       numpy.einsum('zp,mp->zm', tda_eig_vec_ao,
                                    numpy.einsum('tn,mntp->mp',tda_eig_vec_ao,pqrs)
                                   )
                      )
            )
FG1_vlx_ovlp =( numpy.einsum('rp,mp->rm',
                numpy.einsum('rz,zp->rp', ovlp, tda_eig_vec_ao),
                numpy.einsum('tn,mntp->mp',tda_eig_vec_ao,pqrs)
                                   )
            )

FG2_vlx =  numpy.einsum('rz,zm->rm', ovlp,
                       numpy.einsum('zn,nm->zm', tda_eig_vec_ao,
                                    numpy.einsum('tp,mntp->nm',tda_eig_vec_ao,pqrs)
                                   )
                      )
#FG3_vlx =  numpy.einsum('mz,rz->rm', ovlp,
#                       numpy.einsum('zp,rp->rz', tda_eig_vec_ao,
#                                    numpy.einsum('tn,rntp->rp',tda_eig_vec_ao,pqrs)
#                                   )
#                      )
#FG4_vlx =  numpy.einsum('mz,rz->rm', ovlp,
#                       numpy.einsum('zn,rn->rz', tda_eig_vec_ao,
#                                    numpy.einsum('tp,rntp->rn',tda_eig_vec_ao,pqrs)
#                                   )
#                      )
print("eigenvector in MO:")
print(tda_eig_vec_as_mat)
print()
print("eigenvector in AO:")
print(tda_eig_vec_ao)
print()
print("first term:")
print(FG1_vlx_ovlp)
print()
print("first term:")
print(FG1_vlx)
print()
F_2pdm_vlx = 0.5*FG1_vlx #- FG2_vlx - 0.5*FG3_vlx + FG4_vlx
#print(F_2pdm_vlx)
vlx_2pdm_rhs = numpy.einsum('ri,ma->ia', mo_occ, numpy.einsum('ma,rm->ra', mo_vir, F_2pdm_vlx))
print(vlx_2pdm_rhs)    

eigenvector in MO:
[[ 0.    -0.   ]
 [ 0.     0.   ]
 [ 0.    -0.   ]
 [ 0.    -0.   ]
 [ 1.    -0.001]]

eigenvector in AO:
[[-0.      0.     -0.     -0.      0.      0.      0.    ]
 [ 0.     -0.      0.      0.     -0.     -0.     -0.    ]
 [-0.      0.     -0.     -0.      0.      0.      0.    ]
 [-0.      0.     -0.     -0.      0.      0.      0.    ]
 [ 0.1356 -0.9082  0.8054  0.809  -0.     -0.4105 -0.5846]
 [-0.      0.     -0.     -0.      0.      0.      0.    ]
 [ 0.     -0.      0.     -0.     -0.     -0.      0.    ]]

first term:
[[ 0.     0.    -0.    -0.     0.     0.     0.   ]
 [ 0.     0.    -0.    -0.     0.     0.     0.   ]
 [-0.    -0.     0.     0.    -0.    -0.    -0.   ]
 [-0.    -0.     0.     0.    -0.    -0.    -0.   ]
 [ 0.     0.    -0.    -0.     0.039  0.     0.   ]
 [-0.    -0.     0.     0.    -0.    -0.    -0.   ]
 [-0.    -0.     0.     0.    -0.    -0.    -0.   ]]

first term:
[[ 0.     0.    -0.    -0.     0.     0.     0.   ]
 [ 0.     0.    -0

In [101]:
adcc_2pdm_rhs = (numpy.einsum('jakb,ijkb->ia', adcc_DM_ovov, ooov, optimize=True)
                + numpy.einsum('ibjc,jcab->ia', adcc_DM_ovov, ovvv, optimize=True)
                )
print(adcc_2pdm_rhs)

[[-0.0194  0.      0.      0.    ]
 [ 0.0193 -0.      0.      0.    ]
 [ 0.0002 -0.      0.      0.    ]
 [ 0.058  -0.0001  0.      0.    ]
 [ 0.      0.      0.      0.    ]
 [ 0.      0.     -0.0194  0.    ]
 [ 0.      0.      0.0193 -0.    ]
 [ 0.      0.      0.0002 -0.    ]
 [ 0.      0.      0.058  -0.0001]
 [ 0.      0.      0.      0.    ]]
