In [1]:
import veloxchem as vlx
import adcc
from mpi4py import MPI
import sys
import numpy
from scipy.sparse import linalg
from veloxchem.qqscheme import get_qq_scheme
from veloxchem.veloxchemlib import fockmat

numpy.set_printoptions(precision=7, suppress=False)

* Warning * Environment variable OMP_NUM_THREADS not set.
* Warning * Setting OMP_NUM_THREADS to 8.


### Prepare a VeloxChem SCF calculation

In [44]:
# Input settings
#Vmolecule_string = """
#    O 0 0 0
#    H 0 0 1.795239827225189
#    H 1.693194615993441 0 -0.599043184453037"""

molecule_string = """
    O   0.0   0.0   0.0
    H   0.0   1.4   1.1
    H   0.0  -1.4   1.1
    """

#molecule_string = """
#    H 0 0 0
#    H 0 0 1.795239827225189
#    """

basis_set_label = '6-31G'
scf_settings = {'conv_thresh': 1.0e-8}
method_settings = {} #{'xcfun': 'b3lyp', 'grid_level': 4}
rsp_settings = {'conv_thresh': 1.0e-5, 'nstates': 3, 'n_state_deriv': 1} #, 'profiling': 'yes', 'memory_profiling': 'yes', 'memory_tracing': 'yes'

In [45]:
# Communicator and output stream
comm = MPI.COMM_WORLD
ostream = vlx.OutputStream(sys.stdout)

In [46]:
# Molecule and basis set
molecule = vlx.Molecule.read_str(molecule_string, units='au')
basis = vlx.MolecularBasis.read(molecule, basis_set_label)

ostream.print_block(molecule.get_string())
ostream.print_block(basis.get_string('Atomic Basis', molecule))
ostream.flush()

                                              Molecular Geometry (Angstroms)                                              
                                                                                                                          
                          Atom         Coordinate X          Coordinate Y          Coordinate Z                           
                                                                                                                          
                           O           0.000000000000        0.000000000000        0.000000000000                         
                           H           0.000000000000        0.740848095288        0.582094932012                         
                           H           0.000000000000       -0.740848095288        0.582094932012                         
                                                                                                                          
                

In [47]:
dir(basis)
#basis.set_label("6-31g")
#basis.get_label()

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'add_atom_basis',
 'broadcast',
 'get_ao_basis_map',
 'get_avail_basis',
 'get_dimensions_of_basis',
 'get_dimensions_of_primitive_basis',
 'get_label',
 'get_string',
 'get_valence_basis',
 'n_basis_functions',
 'n_primitive_basis_functions',
 'read',
 'set_label']

In [48]:
# SCF
scfdrv = vlx.ScfRestrictedDriver(comm, ostream)
scfdrv.update_settings(scf_settings, method_settings)
scfdrv.compute(molecule, basis)

                                                                                                                          
                                            Self Consistent Field Driver Setup                                            
                                                                                                                          
                   Wave Function Model             : Spin-Restricted Hartree-Fock                                         
                   Initial Guess Model             : Superposition of Atomic Densities                                    
                   Convergence Accelerator         : Two Level Direct Inversion of Iterative Subspace                     
                   Max. Number of Iterations       : 50                                                                   
                   Max. Number of Error Vectors    : 10                                                                   
                

In [49]:
# SCF first-order properties
scf_prop = vlx.ScfFirstOrderProperties(comm, ostream)
scf_prop.compute(molecule, basis, scfdrv.scf_tensors)
scf_prop.print_properties(molecule)

                                                                                                                          
                                                Ground-State Dipole Moment                                                
                                               ----------------------------                                               
                                                                                                                          
                                   X   :        -0.000000 a.u.        -0.000000 Debye                                     
                                   Y   :        -0.000000 a.u.        -0.000000 Debye                                     
                                   Z   :         1.037936 a.u.         2.638170 Debye                                     
                                 Total :         1.037936 a.u.         2.638170 Debye                                     
                

### Excited-State Calculation via CIS (TDHF/TDA)

In [50]:
# TDHF/TDA, i.e. CIS
tda_drv = vlx.TDAExciDriver(comm, ostream)
tda_drv.update_settings(rsp_settings, method_settings)
tda_results = tda_drv.compute(molecule, basis, scfdrv.scf_tensors)
tda_drv.ostream.flush()

                                                                                                                          
                                                     TDA Driver Setup                                                     
                                                                                                                          
                               Number of States                : 3                                                        
                               Max. Number of Iterations       : 150                                                      
                               Convergence Threshold           : 1.0e-05                                                  
                               ERI Screening Scheme            : Cauchy Schwarz + Density                                 
                               ERI Screening Threshold         : 1.0e-15                                                  
                

In [51]:
# RPA = TDHF
# rpa_drv = vlx.LinearResponseEigenSolver(comm, ostream)
# rpa_drv.update_settings(rsp_settings, method_settings)
# rpa_results = rpa_drv.compute(molecule, basis, scfdrv.scf_tensors)
# rpa_drv.ostream.flush()

In [52]:
# Get MO coefficients

nocc = molecule.number_of_alpha_electrons()
mo = scfdrv.scf_tensors['C'] # MO coefficients
mo_occ = mo[:, :nocc]        # occupied
mo_vir = mo[:, nocc:]        # virtual

nocc = mo_occ.shape[1]
nvir = mo_vir.shape[1]

print("nocc =", nocc, "\nnvir =", nvir)

#print("The density matrix:\n", scfdrv.scf_tensors['D'][0])

#occ_occ = numpy.matmul(mo_occ,mo_occ.T)
#print("C CT:\n",occ_occ)

nocc = 5 
nvir = 8


In [53]:
# Get the overlap and Fock matrices
#print(scfdrv.scf_tensors.keys())
fock = scfdrv.scf_tensors['F'][0]
ovlp = scfdrv.scf_tensors['S']
# Transform them from AO to MO basis
# print(numpy.matmul(mo.T, numpy.matmul(ovlp, mo)))
# print(numpy.matmul(mo.T, numpy.matmul(fock, mo)))

In [54]:
# Get the CIS eigenvalues and eigenvectors
tda_eig_vals = tda_results["eigenvalues"]
tda_eig_vecs = tda_results["eigenvectors"]
tda_size = tda_eig_vecs[:,0].shape
tda_eig_vec = tda_eig_vecs[:,0].copy()
tda_eig_vec_as_mat = tda_eig_vec.reshape(nocc, nvir) #/ numpy.sqrt(2.0)
print(tda_eig_vecs)

from veloxchem.veloxchemlib import hartree_in_ev
print(tda_eig_vals*hartree_in_ev())

[[-2.1969534e-11 -4.7324037e-17 -2.3685138e-04]
 [ 2.4381122e-11 -7.2009507e-17  8.5592790e-08]
 [ 2.8870316e-12 -2.0333181e-18  2.5377853e-09]
 [-5.8584022e-04 -1.5691584e-16 -2.4125070e-12]
 [-2.4462298e-11  3.8740253e-17 -1.4504215e-04]
 [ 5.3365882e-13  1.1312430e-17  1.2902770e-04]
 [ 4.9390535e-11 -1.4847076e-16  1.7621922e-07]
 [ 2.5755669e-12 -7.3793808e-17  2.0062350e-04]
 [-1.7244996e-10 -4.8831820e-16  9.7782482e-03]
 [ 3.3480442e-10 -3.4600993e-17  3.4075201e-08]
 [-1.2658065e-10  5.0110828e-17 -7.4068557e-08]
 [ 2.3301623e-03 -3.7622515e-16 -5.6804991e-10]
 [-1.5851054e-10 -5.1887338e-16  2.5724528e-03]
 [ 9.0928263e-11  1.1901764e-15 -1.5503313e-02]
 [-6.6367012e-11  1.0534853e-17 -5.2436674e-09]
 [-1.6938274e-10  7.1654308e-16 -1.3242107e-02]
 [-2.3852313e-10 -1.4409967e-15  1.2559613e-06]
 [ 1.6061177e-11  7.1131841e-16 -1.1195903e-01]
 [-8.3550382e-11  3.7521197e-16 -2.5546970e-02]
 [-1.2061583e-16 -5.1886077e-03  7.4607545e-16]
 [ 1.3024122e-10 -1.9153962e-16  1.25848

In [55]:
# # Get the RPA eigenvalues and eigenvectors
# #rpa_results.keys()
# rpa_eig_vals = rpa_results["eigenvalues"]
# rpa_eig_vecs = rpa_results["eigenvectors"]
# #print(rpa_eig_vecs)

# # Get the excitation and de-excitation part of the first excited state
# rpa_exc_vec = rpa_eig_vecs[:nocc*nvir, 0].copy()
# rpa_deexc_vec = rpa_eig_vecs[nocc*nvir:, 0].copy()
# print()
# print(rpa_exc_vec)
# print()
# print(rpa_deexc_vec)

# # Construct the plus/minus combinations and reshape to matrix form
# xpy = (rpa_exc_vec + rpa_deexc_vec).reshape(nocc, nvir)
# xmy = (rpa_exc_vec - rpa_deexc_vec).reshape(nocc, nvir)
# print()
# print(xpy)
# print()
# print(xmy)

## Use the new OrbitalResponse module

\begin{equation}
   \lambda_{ia} ( \varepsilon_i - \varepsilon_a ) -\sum_{pq} \lambda_{pq} \big( [pq|ai] - [pi|aq] \big) = 
   R_{ia}
   %R^{\text{CIS}}_{ia}
\end{equation}

In [56]:
#from veloxchem.orbitalresponse import OrbitalResponse
from veloxchem.tdaorbitalresponse import TdaOrbitalResponse
from veloxchem.checkpoint import read_rsp_hdf5
from veloxchem.checkpoint import write_rsp_hdf5


orb_resp = TdaOrbitalResponse(comm, ostream)

dft_dict = orb_resp.init_dft(molecule, scfdrv.scf_tensors)
pe_dict = orb_resp.init_pe(molecule, basis)

# The following seems to work
#my_array = numpy.zeros((2,3))
#write_rsp_hdf5('new_specific_orbrsp.chk', [my_array], ['New_OrbRsp_RHS'],
#                  molecule, basis, dft_dict, pe_dict, ostream)
#rhs_mo_from_chk = read_rsp_hdf5('new_specific_orbrsp.chk', ['New_OrbRsp_RHS'],
#                  molecule, basis, dft_dict, pe_dict, ostream)
#print("This is what I am reading from chk....")
#print(rhs_mo_from_chk)

#new_settings = {'checkpoint_file':'very_specific_orbrsp.chk', 'restart':'no'}

rsp_settings['restart'] = 'no'
orb_resp.update_settings(rsp_settings, method_settings)
#print("checkpoint_file =", orb_resp.checkpoint_file)
orb_resp.compute(molecule, basis, scfdrv.scf_tensors, tda_eig_vecs)

print("lambda_ao:")
print(orb_resp.lambda_ao)
print("\nlambda_ao.T:\n", orb_resp.lambda_ao.T)
print("\nlambda_mo:")
print(numpy.matmul(numpy.matmul(mo_occ.T, ovlp), numpy.matmul(orb_resp.lambda_ao, numpy.matmul(ovlp, mo_vir))))
print("\niter_count =", orb_resp.iter_count)
#new_settings = {'checkpoint_file':'very_specific_orbrsp.chk', 'restart':'yes'}


#orb_resp.update_settings(new_settings, method_settings)
#orb_resp.compute(molecule, basis, scfdrv.scf_tensors, tda_eig_vecs)


#print(orb_resp.unrel_dm_ao)

#print("\nOmega in AO basis:\n", orb_resp.omega_ao)

#print(orb_rsp_results.keys())

#print()
#print("lambda multipliers in MO basis:")
#print(orb_rsp_results['lambda_multipliers'])
#print()
#print("lambda multipliers in AO basis:")
#print(orb_rsp_results['lambda_multipliers_ao'])
#print()
#print("omega multipliers in AO basis:")
#print(orb_rsp_results['omega_multipliers'])

                                                                                                                          
                                              Orbital Response Driver Setup                                               
                                                                                                                          
                               Excited State of Interest       : 1                                                        
                               Max. Number of Iterations       : 150                                                      
                               Convergence Threshold           : 1.0e-05                                                  
                                                                                                                          
                                                                                                                          
lambda_ao:
[[ 7.

In [65]:
from veloxchem.checkpoint import read_rsp_hdf5
from veloxchem.checkpoint import write_rsp_hdf5
#numpy.savetxt("lambda_ao.txt", orb_resp.lambda_ao, delimiter=' ')
#numpy.savetxt("omega_ao.txt", orb_resp.omega_ao, delimiter=' ')

write_rsp_hdf5('orbital_response_hf_ref.h5', [orb_resp.lambda_ao, orb_resp.omega_ao],
               ['lambda_tda', 'omega_tda'], molecule, basis, dft_dict, pe_dict, ostream)

True

In [66]:
read_rsp_hdf5('orbital_response_hf_ref.h5', ['lambda_tda', 'omega_tda'],
              molecule, basis, dft_dict, pe_dict, ostream)

[array([[ 7.4208135e-04, -9.0014765e-03,  8.6525342e-03,  9.5486726e-04,
         -7.2618564e-04,  9.5486726e-04, -7.2618564e-04,  2.8110878e-14,
         -1.9635883e-15,  2.5737670e-04, -1.4469940e-03,  8.9348945e-13,
         -9.6398429e-13],
        [-1.6883651e-03,  1.9830638e-02, -1.7761271e-02, -1.5122385e-03,
          1.1041497e-04, -1.5122385e-03,  1.1041497e-04,  8.4766646e-16,
         -2.7983930e-16, -1.9798308e-03,  4.9860068e-03, -3.9687215e-13,
          4.2818471e-13],
        [-1.6317135e-03,  2.0720290e-02, -1.9422247e-02,  6.5955334e-04,
         -8.9890655e-04,  6.5955334e-04, -8.9890655e-04, -2.5270985e-16,
         -4.0894478e-16, -8.6183613e-03,  1.0257384e-02, -6.9183901e-13,
          7.4642394e-13],
        [-6.3180302e-04,  5.0125422e-03, -3.1743750e-03, -1.3015569e-02,
         -1.7799010e-02,  5.2410601e-03,  2.1089111e-02,  1.7647155e-02,
          1.0111905e-02,  9.7420793e-03, -6.6506518e-03,  3.3408951e-12,
         -3.6044845e-12],
        [-8.0015333e

In [16]:
#lambda_ref_ao = numpy.loadtxt("lambda_ao.txt", delimiter=' ')
omega_ref_ao = numpy.loadtxt("omega_ao.txt", delimiter=' ')
#print(lambda_ref_ao)
print(omega_ref_ao)

[[ 2.0672010e+01  2.7102987e-01 -3.4247483e-01 -3.1010258e-02
   5.5320053e-02 -3.1010258e-02  5.5320053e-02  1.1649829e-12
  -3.7532273e-14  1.7962629e-02 -3.5913208e-02 -2.7535827e-10
   1.2962326e-09]
 [ 2.7102987e-01  4.2763296e-01  4.0537242e-01  8.3817779e-02
  -3.5891497e-02  8.3817779e-02 -3.5891497e-02  2.5067860e-14
  -1.5039737e-15  2.3669365e-02 -2.8993157e-03  4.7791583e-10
   4.0817444e-10]
 [-3.4247483e-01  4.0537242e-01  4.5340496e-01  6.1185192e-02
  -9.2671725e-02  6.1185192e-02 -9.2671725e-02 -9.9307006e-15
   1.3788547e-15 -9.1782321e-04 -4.1471146e-03  3.9935086e-10
   2.5159885e-10]
 [-3.1010258e-02  8.3817779e-02  6.1185192e-02  8.4930651e-02
   1.5465275e-02 -9.5972248e-03 -5.7452356e-03  1.1549432e-01
   6.0875881e-02  7.9656206e-02  4.3473272e-02  2.3230286e-11
   3.0665931e-11]
 [ 5.5320053e-02 -3.5891497e-02 -9.2671725e-02  1.5465275e-02
   6.1841003e-02 -5.7452355e-03  6.2163851e-02  3.1751138e-02
   1.6854061e-02 -8.4485426e-03 -1.7237665e-02 -1.4293098e-1

In [17]:
print(orb_resp.lambda_ao.shape)
print(orb_resp.lambda_ao)

(13, 13)
[[ 7.4208135e-04 -9.0014765e-03  8.6525342e-03  9.5486726e-04
  -7.2618564e-04  9.5486726e-04 -7.2618564e-04  5.5952764e-14
  -1.8455698e-15  2.5737670e-04 -1.4469940e-03 -3.6713253e-11
   3.9609867e-11]
 [-1.6883651e-03  1.9830638e-02 -1.7761271e-02 -1.5122385e-03
   1.1041497e-04 -1.5122385e-03  1.1041497e-04  1.6643070e-15
  -8.6393350e-16 -1.9798308e-03  4.9860068e-03 -6.2158515e-12
   6.7062720e-12]
 [-1.6317135e-03  2.0720290e-02 -1.9422247e-02  6.5955334e-04
  -8.9890655e-04  6.5955334e-04 -8.9890655e-04 -3.2224351e-16
  -1.1123569e-15 -8.6183613e-03  1.0257384e-02 -8.0661035e-12
   8.7025057e-12]
 [-6.3180302e-04  5.0125422e-03 -3.1743750e-03 -1.3015569e-02
  -1.7799010e-02  5.2410601e-03  2.1089111e-02  1.7647155e-02
   1.0111905e-02  9.7420793e-03 -6.6506518e-03 -7.8177978e-12
   8.4346146e-12]
 [-8.0015333e-06 -7.8747773e-04  1.1887651e-03 -5.3843090e-03
  -8.2881372e-03  2.9453335e-03  9.4546860e-03  8.0515679e-03
   4.6135871e-03  3.8184513e-03 -3.0849412e-03 -3.2

In [18]:
# Restart using checkpoint, does not improve convergence...
rsp_settings['restart'] = 'yes'
orb_resp.update_settings(rsp_settings, method_settings)
print("checkpoint_file =", orb_resp.checkpoint_file)
orb_resp.compute(molecule, basis, scfdrv.scf_tensors, tda_eig_vecs)

#another_rhs_mo_from_chk = read_rsp_hdf5('new_specific_orbrsp.chk', ['New_OrbRsp_RHS'],
#                  molecule, basis, dft_dict, pe_dict, ostream)

#print("This is what I am reading from chk....")
#print(another_rhs_mo_from_chk)


checkpoint_file = orbrsp.chk
                                                                                                                          
                                              Orbital Response Driver Setup                                               
                                                                                                                          
                               Excited State of Interest       : 1                                                        
                               Max. Number of Iterations       : 150                                                      
                               Convergence Threshold           : 1.0e-05                                                  
                                                                                                                          
                                                                                                              

### Calculate the "gradient" and first-order properties

\begin{equation}
    \vec{\mu} = \frac{\partial L}{\partial \vec{F}}  = \sum_{ij} \gamma_{ij} \, \mu_{ji} + \sum_{ab} \gamma_{ab} \, \mu_{ba} + 2 \sum_{ia} \lambda_{ia} \, \mu_{ai}
\end{equation}
where
$\mu_{pq} = \langle \phi_p | q \vec{r} | \phi_q \rangle %= \int \phi_p q \vec{r} \phi_q d\vec{r}$

In [19]:
from veloxchem.tdagradientdriver import TdaGradientDriver

tdagrad_drv = TdaGradientDriver(comm, ostream, scfdrv, tda_results)
tdagrad_drv.update_settings(rsp_settings, method_settings)
#print(tdagrad_drv.n_state_deriv)
#tdagrad_drv.compute(molecule, basis)
tda_prop = tdagrad_drv.compute_properties(molecule, basis, scfdrv.scf_tensors, orb_resp)

tdagrad_drv.print_properties(molecule, tda_prop)

print()
print("First excited state dipole moments:")
print("ADC(1)/STO-3G unrelaxed dipole moment [a.u.] for water in adcc:")
print("[-0.2107819, -0.,     -0.1423891]")
print()
print("CIS/STO-3G relaxed dipole moment [a.u.] for water in Q-Chem:")
print("[-0.0184062, 0.00000, -0.0076203]")
print("Total dipole: 0.020 a.u., 0.051 Debye")


                                                                                                                          
                                                                                                                          
                                                 Unrelaxed Dipole Moment                                                  
                                                -------------------------                                                 
                                   X   :        -0.000000 a.u.        -0.000000 Debye                                     
                                   Y   :        -0.000000 a.u.        -0.000000 Debye                                     
                                   Z   :        -0.324605 a.u.        -0.825063 Debye                                     
                                 Total :         0.324605 a.u.         0.825063 Debye                                     
                

In [20]:
tdagrad_drv.n_state_deriv
tdagrad_drv.compute(molecule, basis)

                                                                                                                          
                                                   TDA Gradient Driver                                                    
                                                                                                                          
                                                                                                                          
                                              Orbital Response Driver Setup                                               
                                                                                                                          
                               Excited State of Interest       : 1                                                        
                               Max. Number of Iterations       : 150                                                      
                

### Calculate one- and two-particle density matrices

\begin{align}
    \gamma_{ij} &= - \sum_{a} x_{ia} x_{ja} \\
    \gamma_{ab} &= + \sum_{i} x_{ia} x_{ib} \\
    \Gamma_{iajb} &= - x_{ib} x_{ja}
\end{align}

In [21]:
# VeloxChem unrelaxed one-particle density matrix and two-particle density matrix

vlx_dm_oo = -numpy.einsum('ia,ja->ij', tda_eig_vec_as_mat, tda_eig_vec_as_mat)
vlx_dm_vv = numpy.einsum('ia,ib->ab', tda_eig_vec_as_mat, tda_eig_vec_as_mat)
vlx_DM_ovov = -numpy.einsum('ib,ja->iajb', tda_eig_vec_as_mat, tda_eig_vec_as_mat)

# print(vlx_dm_oo)

In the case of RPA, the unrelaxed one-particle density matrices are given by


\begin{equation}
    \gamma_{ij} = -\frac12 \sum_{a} \big[ (x_{ia} + y_{ia})(x_{ja} + y_{ja})
        + (x_{ia} - y_{ia})(x_{ja} - y_{ja}) \big] \\
    \gamma_{ab} = +\frac12 \sum_{i} \big[ (x_{ia} + y_{ia})(x_{ib} + y_{ib})
        + (x_{ia} - y_{ia})(x_{ib} - y_{ib}) \big]
\end{equation}

where $x_{ia}$ is the excitation part of the eigenvectors and $y_{ia}$ the de-excitation part.

In [23]:
# RPA unrelaxed one-particle density matrix

#rpa_dm_oo = -0.5*(numpy.einsum('ia,ja->ij', xpy, xpy)
#             + numpy.einsum('ia,ja->', xmy, xmy))
#rpa_dm_vv = 0.5*(numpy.einsum('ia,ib->ab', xpy, xpy)
#             + numpy.einsum('ia,ib->ab', xmy, xmy))
#
#print(rpa_dm_oo)
#print()
#print(rpa_dm_vv)

### Transform the one-particle density matrices from the MO to the AO basis

\begin{equation}
    \gamma_{\mu \nu} = \sum_{pq} C_{\mu p} \gamma_{pq} C_{\nu q}
\end{equation}

In [24]:
# Transform the one-particle density matrices from MO to AO basis
vlx_dm_oo_in_ao = numpy.matmul(mo_occ, numpy.matmul(vlx_dm_oo, mo_occ.T))
vlx_dm_vv_in_ao = numpy.matmul(mo_vir, numpy.matmul(vlx_dm_vv, mo_vir.T))
vlx_dm_ao = vlx_dm_oo_in_ao + vlx_dm_vv_in_ao

# print("VLX:")
# print(vlx_dm_ao)

#### Transform the excitation vectors to the AO basis
\begin{equation}
    x_{\mu \nu} = \sum_{ia} C_{\mu i} x_{ia} C_{\nu a}
\end{equation}

In [25]:
# Transform the transition density matrix (the excitation vectors) from MO to AO basis
# (will be needed for the two-particle density matrix)
tda_eig_vec_ao = numpy.matmul(mo_occ, numpy.matmul(tda_eig_vec_as_mat, mo_vir.T))
# print(tda_eig_vec_ao)

The MO to AO transformation of the contribution of the two-particle density matrix with the ERI tensor is given as
\begin{align}
\begin{split}
    - \sum_{\sigma \sigma'} \sum_{ijab} x_{i_{\sigma} b_{\sigma}} x_{j_{\sigma'} a_{\sigma'}}
        \langle i_{\sigma} a_{\sigma'} || j_{\sigma'} b_{\sigma} \rangle
    &= - \sum_{ijab} x_{ib} x_{ja} [ 2 (ij|ab) - 4 (ib|aj) ] \\
    &= + \sum_{ijab} x_{ib} x_{ja} [ 4 (ib|aj) - 2 (ij|ab)  ] \\
    &= \sum_{ijab} x_{ib} x_{ja} \sum_{\mu \nu \theta \varphi}
        C_{\mu i} C_{\nu b} C_{\theta a} C_{\varphi j}  [ 4 (\mu \nu | \theta \varphi)
        - 2 (\mu \varphi | \theta \nu) ] \\
    &= \sum_{\mu \nu \theta \varphi} [ 4 (\mu \nu | \theta \varphi)
        - 2 (\mu \varphi | \theta \nu) ]
        \sum_{ib} C_{\mu i} x_{ib} C_{\nu b} \sum_{ja} C_{\varphi j} x_{ja} C_{\theta a} \\
    &= \sum_{\mu \nu \theta \varphi} x_{\mu \nu} x_{\varphi \theta} [ 4 (\mu \nu | \theta \varphi)
        - 2 (\mu \varphi | \theta \nu) ]       \\
    &= \sum_{\mu \nu} x_{\mu \nu} \sum_{\theta \varphi} x_{\varphi \theta} [ 4 (\mu \nu | \theta \varphi)
        - 2 (\mu \varphi | \theta \nu) ]
\end{split}
\end{align}

# Orbital response

\begin{equation}
   -\sum_{pq} \lambda_{pq} \big( [pq|ai] - [pi|aq] \big) + \lambda_{ia} ( \varepsilon_i - \varepsilon_a ) = 
   R_{ia}
   %R^{\text{CIS}}_{ia}
\end{equation}

## Right-hand side

### 1. Contributions from the 1PDMs
\begin{align}
F^\gamma_{ia} &= \sum_{\theta,\varphi}C^\alpha_{\varphi i}C^\alpha_{\theta a}\sum_{\mu,\nu,\sigma}\gamma^\sigma_{\mu\nu}(\mu\nu|\theta \varphi)-\sum_{\theta,\varphi}C^\alpha_{\varphi i}C^\alpha_{\theta a}\sum_{\mu,\nu}\gamma^{\alpha}_{\mu\nu}(\mu\varphi|\theta\nu)\\
&= \sum_{\theta,\varphi}C^\alpha_{\varphi i}C^\alpha_{\theta a} 2F^{1,\alpha}_{\varphi\theta}-\sum_{\theta,\varphi}C^\alpha_{\varphi i}C^\alpha_{\theta a}F^{2,\alpha}_{\varphi\theta}\\
&= \sum_{\theta,\varphi}C^\alpha_{\varphi i}C^\alpha_{\theta a}F_{\varphi\theta}
\end{align}

### 2. Contributions from the 2PDMs

\begin{align}
F^\Gamma_{ia} &= ~~ \sum_{\mu,\zeta}C^\alpha_{\mu i}C^\alpha_{\zeta a} \Big[\sum_{\rho,\varphi}S_{\rho\zeta}x^\alpha_{\varphi\rho}\sum_{\nu,\theta}x^\alpha_{\theta\nu}(\mu\nu|\theta\varphi)-\sum_{\rho,\varphi}S_{\rho\zeta}x^\alpha_{\varphi\rho}\sum_{\theta,\nu,\sigma} x^\sigma_{\theta\nu}(\mu\varphi|\theta\nu) \Big] \\
&~~~ -\sum_{\mu,\zeta}C^\alpha_{\mu i}C^\alpha_{\zeta a} \Big[ \sum_{\rho,\varphi}S_{\mu\rho}x^\alpha_{\rho\varphi}\sum_{\nu,\theta}x^\alpha_{\nu\theta}(\zeta\nu|\theta\varphi)-\sum_{\rho,\varphi} S_{\mu\rho}x^\alpha_{\rho\varphi}\sum_{\theta,\nu,\sigma}x^\sigma_{\nu\theta}(\zeta\varphi|\theta\nu) \Big] \\
&= - \sum_{\mu,\zeta}C^\alpha_{\mu i}C^\alpha_{\zeta a} \sum_{\rho,\varphi}S_{\rho\zeta}x^\alpha_{\varphi\rho}\Big[ 2\sum_{\theta,\nu} x^\alpha_{\theta\nu}(\mu\varphi|\theta\nu)- \sum_{\nu,\theta}x^\alpha_{\theta\nu}(\mu\nu|\theta\varphi) \Big] \\
&~~~~ +\sum_{\mu,\zeta}C^\alpha_{\mu i}C^\alpha_{\zeta a} \sum_{\rho,\varphi}S_{\mu\rho}x^\alpha_{\rho\varphi}\Big[ 2\sum_{\theta,\nu} x^\alpha_{\nu\theta}(\zeta\varphi|\theta\nu)- \sum_{\nu,\theta}x^\alpha_{\nu\theta}(\zeta\nu|\theta\varphi) \Big] \\
&= - \sum_{\mu,\zeta}C^\alpha_{\mu i}C^\alpha_{\zeta a} \sum_{\rho,\varphi}S_{\rho\zeta}x^\alpha_{\varphi\rho}\Big[ \sum_{\theta,\nu} x^\alpha_{\theta\nu} \big[ 2 (\mu\varphi|\theta\nu)- (\mu\nu|\theta\varphi) \big] \Big] \\
&~~~~ +\sum_{\mu,\zeta}C^\alpha_{\mu i}C^\alpha_{\zeta a} \sum_{\rho,\varphi}S_{\mu\rho}x^\alpha_{\rho\varphi}\Big[ \sum_{\theta,\nu} x^\alpha_{\nu\theta} \big[ 2(\zeta\varphi|\theta\nu)- (\zeta\nu|\theta\varphi) \big] \Big]
\end{align}

In [26]:
# Calculate two different parts and transform the sum to MO
nao = mo.shape[0]

pqrs = numpy.zeros((nao, nao, nao, nao))
eri_drv_pqrs = vlx.ElectronRepulsionIntegralsDriver(comm)
eri_drv_pqrs.compute_in_mem(molecule, basis, pqrs)

F1_vlx = numpy.einsum('mn,mntp->pt', vlx_dm_ao, pqrs)
F2_vlx = numpy.einsum('mn,mptn->pt', vlx_dm_ao, pqrs)
# The density matrices already have a factor of 2 (for alpha and beta spin)
# hence a factor of 0.5 where the other spin part actually vanishes
F_1pdm_vlx = F1_vlx - 0.5*F2_vlx
vlx_1pdm_rhs = numpy.einsum('pi,pa->ia', mo_occ, numpy.einsum('ta,pt->pa', mo_vir, F_1pdm_vlx))
print(vlx_1pdm_rhs)

[[-8.2846131e-03 -2.2151928e-16  4.5112943e-16 -1.4504656e-10
  -1.1504816e-02  7.9106582e-03  1.0142291e-15  1.1597459e-02]
 [ 7.1800179e-02  3.7132738e-15 -3.8840754e-15  9.3710330e-11
   3.4153496e-02 -5.7455558e-02 -3.6433936e-15 -8.6266767e-02]
 [ 6.5858695e-15 -9.1907823e-02 -4.8446246e-02 -1.2366306e-10
   2.6307542e-15 -3.3398341e-15 -9.9084176e-02  1.7899845e-15]
 [ 5.9554564e-02  5.6548483e-16 -3.5415199e-15  4.4717172e-11
   1.2576742e-01  1.0965336e-02  1.8002441e-17  8.8855364e-03]
 [ 3.4774333e-11  9.5922830e-11 -1.3676464e-11  4.6750483e-02
  -9.0532807e-12  9.2053815e-11  1.0625046e-10 -1.6231154e-10]]


# Start -- Orbital Response 

In [27]:
# Set up ERI driver:
nao = mo.shape[0]
#Probably these will be properties of our OrbitalResponseSolver?
qq_type = 'QQ_DEN'
eri_thresh = 1.0e-15
eri_drv = vlx.ElectronRepulsionIntegralsDriver(comm)
screening = eri_drv.compute(get_qq_scheme(qq_type),
                            eri_thresh, molecule, basis)
# print(dir(screening))
# print(screening.get_screener(7))


In [28]:
# Use AODensityMatrix object to compute a Fock-like matrix
# expect something like F_{\varphi\theta}, equation above
# see linearsolver.py; we have to create a linear solver object:
# 
# from veloxchem.linearsolver import LinearSolver
from veloxchem.veloxchemlib import AOFockMatrix
from veloxchem.veloxchemlib import AODensityMatrix
from veloxchem.veloxchemlib import denmat

#Create all AODensityMatrices needed for the RHS
#1PDM contribution:
ao_density_1pdm = AODensityMatrix([vlx_dm_ao], denmat.rest)

#2PDM contribution
ao_density_2pdm_1 = AODensityMatrix([tda_eig_vec_ao.T], denmat.rest)
ao_density_2pdm_2 = AODensityMatrix([tda_eig_vec_ao], denmat.rest)

#We only use one of the terms (i.e. ao_density_2pdm_2 -- coresponding to tda_eig_vec_ao)
#because we can get the other as its transpose
ao_density_RHS_all = AODensityMatrix([vlx_dm_ao, tda_eig_vec_ao], denmat.rest)

print("Single terms:")
print("1PDM")
print(ao_density_1pdm)
print()
print("2PDM:")
print(ao_density_2pdm_1)
print()
print(ao_density_2pdm_2)

print("ALL RHS:")
print(ao_density_RHS_all)

Single terms:
1PDM
Density Type: Restricted Density Matrix
[Dimension 13 x 13]
     0.00830043    -0.01913146    -0.09384418     0.00958471     0.08260166     0.00958471     0.08260166    -0.00000000    -0.00000000    -0.02970625    -0.03374994    -0.00000000    -0.00000000
    -0.01913146     0.04409375     0.21628017    -0.02208978    -0.19036719    -0.02208978    -0.19036719     0.00000000     0.00000000     0.06845866     0.07777875     0.00000000     0.00000000
    -0.09384418     0.21628017     1.06080599    -0.10834618    -0.93369495    -0.10834618    -0.93369495     0.00000000     0.00000000     0.33575121     0.38146773     0.00000000     0.00000000
     0.00958471    -0.02208978    -0.10834618     0.01106600     0.09536381     0.01106600     0.09536381    -0.00000000    -0.00000000    -0.03429254    -0.03896177    -0.00000000    -0.00000000
     0.08260166    -0.19036719    -0.93369495     0.09536381     0.82181125     0.09536381     0.82181125    -0.00000000    -0.00000000  

In [29]:
fock_rhs_1pdm = AOFockMatrix(ao_density_1pdm)
fock_rhs_2pdm_1 = AOFockMatrix(ao_density_2pdm_1)
fock_rhs_2pdm_2 = AOFockMatrix(ao_density_2pdm_2)

fock_RHS_all = AOFockMatrix(ao_density_RHS_all)
fock_flag = fockmat.rgenjk
for i in range(fock_RHS_all.number_of_fock_matrices()):
    fock_RHS_all.set_fock_type(fock_flag, i)
    
fock_rhs_2pdm_1.set_fock_type(fock_flag, 0)
fock_rhs_2pdm_2.set_fock_type(fock_flag, 0)

eri_drv.compute(fock_rhs_1pdm, ao_density_1pdm, molecule, basis, screening) 
eri_drv.compute(fock_rhs_2pdm_1, ao_density_2pdm_1, molecule, basis, screening) 
eri_drv.compute(fock_rhs_2pdm_2, ao_density_2pdm_2, molecule, basis, screening) 

eri_drv.compute(fock_RHS_all, ao_density_RHS_all, molecule, basis, screening)

print("Fock matrices, single terms:")
print("Fock-1PDM")
print(fock_rhs_1pdm)
print()
print("Fock-2PDM:")
print(fock_rhs_2pdm_1)
print()
print(fock_rhs_2pdm_2)

print("Fock-ALL RHS:")
print(fock_RHS_all)



Fock matrices, single terms:
Fock-1PDM
Fock Type: Restricted 2J + K Matrix
Density Identifier: 0
[Dimension 13 x 13]
    -1.01787249    -0.19435200    -0.14302263    -0.03034627    -0.05790080    -0.03034627    -0.05790080     0.00000000     0.00000000     0.02715864     0.00377884     0.00000000    -0.00000000
    -0.19435200    -0.69735592    -0.42012581    -0.09669843    -0.15164230    -0.09669843    -0.15164230     0.00000000     0.00000000     0.01703011     0.04336583    -0.00000000    -0.00000000
    -0.14302263    -0.42012581    -0.39357934    -0.11559136    -0.21313345    -0.11559136    -0.21313345     0.00000000     0.00000000     0.06803363     0.08473112    -0.00000000    -0.00000000
    -0.03034627    -0.09669843    -0.11559136    -0.15358404    -0.13462428    -0.02508406    -0.07252093    -0.09490577    -0.09327323    -0.04045431    -0.05349916     0.00000000     0.00000000
    -0.05790080    -0.15164230    -0.21313345    -0.13462428    -0.20372405    -0.07252093    -0.15

In [30]:
#Transform the 1PDM contribution to the RHS to MO basis:
MO_rhs_1pdm = numpy.einsum('pi,pa->ia', mo_occ,
                    numpy.einsum('ta,pt->pa', mo_vir, 0.5*fock_RHS_all.alpha_to_numpy(0)))

print("\nIn MO basis, 1PDM contribution to the RHS, using one-shot Fock-build?:")
print(MO_rhs_1pdm)
print()
print("Original, for comparison:")
print(vlx_1pdm_rhs)


In MO basis, 1PDM contribution to the RHS, using one-shot Fock-build?:
[[-8.2846131e-03 -1.7497310e-16  4.3549300e-16 -1.4504656e-10
  -1.1504816e-02  7.9106582e-03  9.7769914e-16  1.1597459e-02]
 [ 7.1800179e-02  3.8665810e-15 -3.9827136e-15  9.3710330e-11
   3.4153496e-02 -5.7455558e-02 -3.7397339e-15 -8.6266767e-02]
 [ 6.6840131e-15 -9.1907823e-02 -4.8446246e-02 -1.2366306e-10
   2.6533834e-15 -3.3249395e-15 -9.9084176e-02  1.9451930e-15]
 [ 5.9554564e-02  5.2268486e-16 -3.7583263e-15  4.4717172e-11
   1.2576742e-01  1.0965336e-02  5.8907529e-17  8.8855364e-03]
 [ 3.4774333e-11  9.5922830e-11 -1.3676464e-11  4.6750483e-02
  -9.0532807e-12  9.2053815e-11  1.0625046e-10 -1.6231154e-10]]

Original, for comparison:
[[-8.2846131e-03 -2.2151928e-16  4.5112943e-16 -1.4504656e-10
  -1.1504816e-02  7.9106582e-03  1.0142291e-15  1.1597459e-02]
 [ 7.1800179e-02  3.7132738e-15 -3.8840754e-15  9.3710330e-11
   3.4153496e-02 -5.7455558e-02 -3.6433936e-15 -8.6266767e-02]
 [ 6.5858695e-15 -9.19078

In [31]:
#Contract with excitation vector, overlap integrals and transform the 2PDM contribution to the RHS to MO basis:
#print(fock_RHS_all.alpha_to_numpy(1))

#LR_2pdm_F1 =  numpy.einsum('rz,mr->mz', ovlp,
#                numpy.einsum('pr,mp->mr', tda_eig_vec_ao, 0.5*fock_RHS_all.alpha_to_numpy(1).T))
#LR_2pdm_F2 =  numpy.einsum('mr,rz->mz', ovlp,
#                numpy.einsum('rp,zp->rz', tda_eig_vec_ao, 0.5*fock_RHS_all.alpha_to_numpy(1)))

MO_rhs_2pdm = numpy.einsum('mi,ma->ia', mo_occ, 
                                 numpy.einsum('za,mz->ma', mo_vir,  
                                              (numpy.einsum('mr,rz->mz', ovlp,
                                                            numpy.einsum('rp,zp->rz',
                                                                         tda_eig_vec_ao, 
                                                                         0.5*fock_RHS_all.alpha_to_numpy(1))))
                                              
                                              -(numpy.einsum('rz,mr->mz', ovlp,
                                                             numpy.einsum('pr,mp->mr',
                                                                          tda_eig_vec_ao,
                                                                          0.5*fock_RHS_all.alpha_to_numpy(1).T))))
                          )

print(MO_rhs_2pdm)

[[ 1.1668001e-02  3.5893873e-17 -7.0949093e-17  2.8150978e-12
   1.1789140e-03 -5.6989128e-04 -8.2238924e-17 -6.3698941e-04]
 [-2.8244349e-02 -8.8984930e-17  1.7720116e-16 -9.6778631e-11
  -2.8567154e-03  1.3801051e-03  2.0601812e-16  1.5566595e-03]
 [-2.7077840e-15 -9.9102891e-19 -1.6697686e-18  6.2294203e-11
  -2.6792891e-16  1.2627455e-16  2.3255395e-18  1.5293589e-16]
 [-3.7280062e-02 -1.2230091e-16  2.3189859e-16 -6.7556253e-12
  -3.7446451e-03  1.8164542e-03  2.5761651e-16  1.9253785e-03]
 [-1.2805801e-10 -1.3592809e-10  3.2860938e-11  2.2717863e-02
   1.3921351e-11  3.8872991e-11 -8.4586465e-11  1.4192119e-11]]


In [32]:
RHS = MO_rhs_1pdm+MO_rhs_2pdm

## Left-hand side
### Initial guess for Lagrange multipliers $\boldsymbol{\lambda}$

\begin{equation}
    \lambda_{ia}^{(0)} = \frac{R_{ia}}{\varepsilon_i - \varepsilon_a}
\end{equation}

In [33]:
#Construct Initial Guess: lambda_guess=RHS/(epsilon_i-epsilon_a)
orb_ene = scfdrv.scf_tensors['E']
eocc = orb_ene[:nocc]
evir = orb_ene[nocc:]
eov = -evir + eocc.reshape(-1, 1)
#print(eov)

lambda_guess = RHS / eov

print(lambda_guess)

[[-1.6293757e-04  6.6666923e-18 -1.6864193e-17  6.5477774e-12
   4.7450179e-04 -3.3699453e-04 -4.0809324e-17 -4.9244858e-04]
 [-2.7697118e-02 -2.2627845e-15  1.5698737e-15  1.2128919e-12
  -1.2181483e-02  2.1645009e-02  1.2849024e-15  2.7640337e-02]
 [-4.3022926e-15  9.0010298e-02  2.7282536e-02  3.2619147e-11
  -1.2418778e-15  1.6468245e-15  4.7142135e-02 -8.6830034e-16]
 [-2.8874244e-02 -4.6111191e-16  2.1728591e-15 -2.1960926e-11
  -6.9014883e-02 -7.1424897e-03 -1.6240017e-16 -4.7760189e-03]
 [ 1.3145918e-10  4.9605310e-11 -1.2288965e-11 -4.1678541e-02
  -2.8531069e-12 -7.5780413e-11 -1.1479391e-11  6.7273397e-11]]


### Contraction of the initial guess for $\boldsymbol{\lambda}$ with two-electron integrals

using $p=j, q=b$ as well as $p=b, q=j$ with the condition $\lambda_{pq} = \lambda_{qp}$ and assuming real orbitals, the equation is obtained as
\begin{align}
-\sum_{pq} \lambda_{pq} \big( [pq|ai] - [pi|aq] \big)
    &= -\sum_{\varphi \theta} C_{\varphi i} C_{\theta a} \sum_{\mu \nu}
        \lambda_{\mu \nu} \big[ 4 (\mu \nu | \varphi \theta)
        - (\mu \theta | \varphi \nu) - (\nu \theta | \varphi \mu) \big] \\
    %+ (\varepsilon_a - \varepsilon_i ) \gamma_{ia}
    &= - \sum_{\varphi \theta} \big[ C_{\varphi i} C_{\theta a} + C_{\theta i} C_{\varphi a} \big]
        \sum_{\mu \nu} \lambda_{\mu \nu} \big[ 2 (\mu \nu | \varphi \theta) - (\mu \theta | \varphi \nu) \big]
\end{align}

#### Full LHS 
\begin{equation}
   -\sum_{pq} \lambda_{pq} \big( [pq|ai] - [pi|aq] \big) + \lambda_{ia} ( \varepsilon_i - \varepsilon_a )
\end{equation}

## Solution via Conjugate Gradient

To solve: $\mathbf{A} \mathbf{x} = \mathbf{b}$

However, we do not "know" the matrix $\mathbf{A}$, only the matrix-vector product $\mathbf{Ax}$.
Thus, define it as a linear operator with a vector $\mathbf{x}$ as an argument.

### Defining a linear operator

In [34]:
lambda_guess_ao = numpy.matmul(mo_occ, numpy.matmul(lambda_guess, mo_vir.T))
    
#Create AODensityMatrix object from lambda in AO
ao_density_lambda_guess = AODensityMatrix([lambda_guess_ao], denmat.rest)
fock_lambda = AOFockMatrix(ao_density_lambda_guess)
fock_lambda.set_fock_type(fock_flag, 0)

#Matrix-vector product routine for conjugate gradient:
def OrbRsp_LHS_mvp(v):
    """Function to carry out matrix multiplication
    of Lagrange multipier vector with orbital Hessian
    matrix, using AODensityMatrix, AOFockMatrix
    
    v: lambda at current iteration"""
    
    #lambda_mo = v.reshape(nocc,nvir)
    
    # Transform to AO
    lambda_ao = numpy.matmul(mo_occ, numpy.matmul(v.reshape(nocc,nvir), mo_vir.T))
    
    #Create AODensityMatrix object from lambda in AO
    ao_density_lambda = AODensityMatrix([lambda_ao], denmat.rest)
    
    #Create a Fock Matrix Object (initialized with zeros)    
    eri_drv.compute(fock_lambda, ao_density_lambda, molecule, basis, screening) 
    
    #Transform to MO basis (symmetrized w.r.t. occ. and virt.) and add diagonal part
    lambda_mo = (-( numpy.matmul(mo_occ.T, numpy.matmul(fock_lambda.alpha_to_numpy(0), mo_vir)) 
                + numpy.matmul(mo_vir.T, numpy.matmul(fock_lambda.alpha_to_numpy(0), mo_occ)).T )
                +v.reshape(nocc,nvir) * eov) 
    
    return lambda_mo.reshape(nocc*nvir)

In [35]:
#OrbRsp_LHS_mvp(lambda_guess.reshape(nocc*nvir))
A = linalg.LinearOperator((nocc*nvir,nocc*nvir), matvec=OrbRsp_LHS_mvp)
solution, w = linalg.cg(A=A, b=RHS.reshape(nocc*nvir), x0=lambda_guess.reshape(nocc*nvir), tol=1e-8, maxiter=25)

lambda_OV = solution.reshape(nocc,nvir)
print(lambda_OV)
print(fock_lambda)

[[-3.9599169e-04  2.4112592e-13 -1.3710803e-14  5.9682127e-12
   4.4427239e-04 -7.8942415e-05  2.6483984e-14 -4.7993490e-05]
 [-1.7974881e-02 -1.1863907e-15  1.4889516e-15  2.3251366e-12
  -1.0497864e-02  1.5199539e-02  1.7859343e-15  1.8563782e-02]
 [-3.9512272e-15  8.3104279e-02  2.6976751e-02  4.2287606e-11
  -1.3542269e-15  1.8196850e-15  3.5217007e-02 -1.4089554e-16]
 [-9.8476569e-03  1.3590228e-16  2.2416239e-15 -2.4055719e-11
  -5.0719754e-02 -5.9744011e-04 -4.3216712e-18 -1.9564901e-03]
 [ 2.4148290e-10  7.8289205e-11 -1.3667930e-11 -5.9236920e-04
   6.7994064e-12 -1.0232368e-10 -1.1748698e-11  7.3498146e-11]]
Fock Type: Restricted general 2J + K Matrix
Density Identifier: 0
[Dimension 13 x 13]
     0.14949297     0.02794743     0.02145771     0.00484315     0.00910918     0.00484315     0.00910918    -0.00000000    -0.00000000    -0.00047718     0.00008223    -0.00000000    -0.00000000
     0.02675366     0.06489205     0.05103846     0.01850944     0.02776059     0.01850944  

# Omega Multipliers (for Overlap Matrix)

## General Equation:
\begin{equation}
2\left(\gamma'_{ut}+\lambda_{ut}\right)\epsilon_u +2\sum_{p,q}\left(\gamma'_{pq}+\lambda_{pq}\right)\langle{pu||qt}\rangle\delta_{t\epsilon_o}+\sum_{p,q,r}\Gamma'_{tpqr}\langle{up||qr}\rangle+2\omega_{ut}=0\
\end{equation}

## VV block ($\alpha$ block)
\begin{equation}
2\gamma'_{ab}\epsilon_a +\sum_{p,q,r}\Gamma'_{bpqr}\langle{ap||qr}\rangle+2\omega_{ab}=0\\
2\gamma'_{ab}\epsilon_a +\sum_{p,q,r}\Gamma'_{bpqr}([aq|pr]-[ar|pq])+2\omega_{ab} = 0\\
2\gamma'_{ab}\epsilon_a +\sum_{p,q,r}\Gamma'_{bpqr}[(aq|pr)(\alpha\sigma'|\sigma\sigma'')-(ar|pq)(\alpha\sigma''|\sigma\sigma')]+2\omega_{ab} = 0\\
2\gamma'_{ab}\epsilon_a +\sum_{p,q,r}\Gamma'_{pbrq}[(aq|pr)(\alpha\sigma'|\sigma\sigma'')-(ar|pq)(\alpha\sigma''|\sigma\sigma')]+2\omega_{ab} = 0\\
2\gamma'_{ab}\epsilon_a +2\sum_{i,c,j}\Gamma'_{ibjc}[(ac|ij)(\alpha\sigma'|\sigma\sigma'')-(aj|ic)(\alpha\sigma''|\sigma\sigma')]+2\omega_{ab} = 0\\
2\gamma'_{ab}\epsilon_a -2\sum_{i,c,j}x_{ic}x_{jb}[(ac|ij)(\alpha\sigma'|\sigma\sigma'')-(aj|ic)(\alpha\sigma''|\sigma\sigma')]+2\omega_{ab} = 0\\
2\gamma'_{ab}\epsilon_a -2\sum_{i,c,j}x_{ic}x_{jb}[(ac|ij)(\alpha\alpha|\alpha\alpha)-(aj|ic)(\alpha\alpha|\sigma\sigma)]+2\omega_{ab} = 0\\
2\gamma'_{ab}\epsilon_a + 2\sum_{i,c,j}x_{ic}x_{jb}[2(aj|ic)-(ac|ij)]+2\omega_{ab} = 0\\
\gamma'_{ab}\epsilon_a + \sum_{\mu\nu\theta\varphi}C_{\theta a}[2(\theta\nu|\mu\varphi)-(\theta\varphi|\mu\nu)]\sum_{j}x_{jb}C_{\nu j}\sum_{i,c}C_{\mu i}x_{ic}C_{\varphi c}+\omega_{ab} = 0\\
\gamma'_{ab}\epsilon_a + \sum_{\mu\nu\theta\varphi}C_{\theta a}[2(\theta\nu|\mu\varphi)-(\theta\varphi|\mu\nu)]\sum_{j}C_{\nu j}x_{jb}x_{\mu\varphi}+\omega_{ab} = 0\\
\gamma'_{ab}\epsilon_a + \sum_{\mu\nu\theta\varphi}C_{\theta a}[2(\theta\nu|\mu\varphi)-(\theta\varphi|\mu\nu)]x_{\nu b}x_{\mu\varphi}+\omega_{ab} = 0\\
\gamma'_{ab}\epsilon_a + \sum_{\mu\nu\theta\varphi}C_{\theta a}[2(\theta\nu|\mu\varphi)-(\theta\varphi|\mu\nu)]\sum_{\rho,\zeta}x_{\nu \zeta}S_{\zeta\rho}C_{\rho b}x_{\mu\varphi}+\omega_{ab} = 0\\
\gamma'_{ab}\epsilon_a + \sum_{\theta\rho}C_{\theta a}C_{\rho b}\sum_{\nu,\zeta}x_{\nu \zeta}S_{\zeta\rho} \sum_{\mu,\varphi}[2(\theta\nu|\mu\varphi)-(\theta\varphi|\mu\nu)]x_{\mu\varphi}+\omega_{ab} = 0\\
%
\gamma'_{ab}\epsilon_a = \gamma'_{ab} (F_{ab} \delta_{ab})
\end{equation}


In [36]:
#omega_VV = numpy.zeros(vlx_dm_vv.shape)
omega_VV = -numpy.einsum('ta,tb->ab', mo_vir, 
                                 numpy.einsum('rb,tr->tb', mo_vir,  
                                              (numpy.einsum('zr,tz->tr', ovlp,
                                                            numpy.einsum('nz,tn->tz',
                                                                         tda_eig_vec_ao, 
                                                                         0.5*fock_RHS_all.alpha_to_numpy(1).T
                                                                        )
                                                           )
                                              )
                                             )
                        )
# print("MO virtual energies:")
# print(evir)
# print()
omega_VV_wo_e = omega_VV.copy()
eps_omega_VV = numpy.zeros(omega_VV.shape)
for a in range(evir.shape[0]):
    omega_VV[a,:]-=evir[a]*0.5*vlx_dm_vv[a,:]
    eps_omega_VV[a,:] = -evir[a]*0.5*vlx_dm_vv[a,:]
print(omega_VV)
# print("1PDM")
# print(vlx_dm_vv/2)

[[ 7.3780146e-02  2.4544181e-16 -4.4173546e-16  2.9572276e-11
   7.4426038e-03 -3.6011994e-03 -5.5623666e-16 -3.9680797e-03]
 [ 1.1165675e-16  9.1151443e-18  1.4030887e-17 -1.0725616e-12
  -2.2663471e-17  2.1282298e-17 -1.2352815e-17 -9.8613524e-17]
 [-4.3092267e-16  9.5587372e-18 -7.2668493e-18  1.9337784e-12
  -3.5688098e-17  2.3377994e-17 -1.4508451e-18  3.7296199e-17]
 [-1.2124909e-10  8.1490448e-13 -1.0580976e-12  8.7936203e-06
  -1.3918858e-11  7.3518588e-12 -4.1504278e-12  6.6500864e-12]
 [ 7.4426038e-03  6.7083986e-17 -5.4349627e-17  4.7154986e-12
   7.5077585e-04 -3.6327253e-04 -7.6925336e-17 -4.0028173e-04]
 [-3.6011994e-03 -3.2640520e-17  2.6828709e-17 -3.6349252e-12
  -3.6327253e-04  1.7577407e-04  3.9305941e-17  1.9368145e-04]
 [-4.5458107e-16 -2.1405832e-18 -1.1002184e-17  6.0363852e-12
  -2.3416434e-17  6.0181489e-18  4.6369315e-18  8.3585601e-17]
 [-3.9680797e-03 -4.7923338e-17  3.9821968e-17  8.6971737e-14
  -4.0028174e-04  1.9368146e-04  5.7483694e-17  2.1341319e-04]]

## OV block ($\alpha$ block)
\begin{equation}
2\lambda_{ia}\epsilon_i + \sum_{p,q,r}\Gamma'_{apqr}\langle{ip||qr}\rangle+2\omega_{ia}=0\\
2\lambda_{ia}\epsilon_i + \sum_{p,q,r}\Gamma'_{parq}[(iq|pr)(\alpha\sigma'|\sigma\sigma'')-(ir|pq)(\alpha\sigma''|\sigma\sigma')]+2\omega_{ia}=0\\
2\lambda_{ia}\epsilon_i + 2\sum_{j,b,k}\Gamma'_{jakb}[(ib|jk)(\alpha\sigma'|\sigma\sigma'')-(ik|jb)(\alpha\sigma''|\sigma\sigma')]+2\omega_{ia}=0\\
\lambda_{ia}\epsilon_i + \sum_{j,b,k}x_{jb}x_{ka}[2(ik|jb)-(ib|jk)]+\omega_{ia}=0\\
\lambda_{ia}\epsilon_i + \sum_{\mu,\nu,\theta,\varphi}\sum_{j,b,k}C_{\mu i}C_{\nu j}C_{\theta k}C_{\varphi b}x_{jb}x_{ka}[2(\mu\theta|\nu\varphi)-(\mu\varphi|\nu\theta)]+\omega_{ia}=0\\
\lambda_{ia}\epsilon_i + \sum_{\mu,\nu,\theta,\varphi}C_{\mu i}x_{\nu\varphi}\sum_{\rho,\zeta}x_{\theta \rho}S_{\rho\zeta}C_{\zeta a}[2(\mu\theta|\nu\varphi)-(\mu\varphi|\nu\theta)]+\omega_{ia}=0\\
\lambda_{ia}\epsilon_i + \sum_{\mu, \zeta}C_{\mu i}C_{\zeta a}\sum_{\rho,\theta}x_{\theta \rho}S_{\rho\zeta}\sum_{\nu,\varphi}[2(\mu\theta|\nu\varphi)-(\mu\varphi|\nu\theta)]x_{\nu\varphi}+\omega_{ia}=0\\
\end{equation}

In [37]:
omega_OV = numpy.zeros((nocc,nvir))
omega_OV = -numpy.einsum('mi,ma->ia', mo_occ, 
                                 numpy.einsum('za,mz->ma', mo_vir,  
                                              (numpy.einsum('rz,mr->mz', ovlp,
                                                            numpy.einsum('tr,mt->mr',
                                                                         tda_eig_vec_ao, 
                                                                         0.5*fock_RHS_all.alpha_to_numpy(1).T
                                                                        )
                                                           )
                                              )
                                             )
                        )
# print("MO occupied energies:")
#print(eocc)
# print()
for i in range(nocc):
    omega_OV[i,:]-=eocc[i]*lambda_OV[i,:]
print(omega_OV)

[[ 3.5256943e-03  4.9570961e-12 -2.8193780e-13  1.2748567e-10
   1.0310201e-02 -2.1923355e-03  5.4437403e-13 -1.6141012e-03]
 [-5.2785092e-02 -1.7105975e-15  2.2094908e-15 -7.8294533e-12
  -1.7184604e-02  2.2135045e-02  2.6398643e-15  2.6869728e-02]
 [-5.5385779e-15  5.9606679e-02  1.9349118e-02  3.0063201e-11
  -1.2403726e-15  1.4320900e-15  2.5259455e-02  5.5760286e-17]
 [-4.2851585e-02 -4.6126795e-17  1.4960113e-15 -2.8472905e-11
  -3.2391787e-02  1.4830220e-03  2.5975675e-16  9.0132009e-04]
 [ 2.1026009e-11  5.8079306e-11 -1.4883106e-11 -2.6974738e-04
  -2.5103493e-11 -2.5452973e-11 -8.3023333e-12  3.4664988e-11]]


## OO block ($\alpha$ block)
\begin{equation}
2\gamma'_{ij}\epsilon_i +2\sum_{p,q}\left(\gamma'_{pq}+\lambda_{pq}\right)\langle{pi||qj}\rangle+\sum_{p,q,r}\Gamma'_{jpqr}\langle{ip||qr}\rangle+2\omega_{ij}=0\\
2\gamma'_{ij}\epsilon_i +2\sum_{p,q}\left(\gamma'_{pq}+\lambda_{pq}\right)([pq|ij]-[pj|iq])+\sum_{p,q,r}\Gamma'_{jpqr}([iq|pr]-[ir|pq])+2\omega_{ij}=0\\
2\gamma'_{ij}\epsilon_i +2\sum_{p,q}\left(\gamma'_{pq}+\lambda_{pq}\right)[(pq|ij)(\sigma\sigma'|\alpha\alpha)-(pj|iq)(\sigma\alpha|\alpha\sigma')]+\sum_{p,q,r}\Gamma'_{jpqr}[(iq|pr)(\alpha\sigma'|\sigma\sigma'')-(ir|pq)(\alpha\sigma''|\sigma\sigma')]+2\omega_{ij}=0\\
2\gamma'_{ij}\epsilon_i +2\sum_{p,q}\left(\gamma'_{pq}+\lambda_{pq}\right)[2(pq|ij)-(pj|iq)]+\sum_{p,q,r}\Gamma'_{jpqr}[(iq|pr)(\alpha\sigma'|\sigma\sigma'')-(ir|pq)(\alpha\sigma''|\sigma\sigma')]+2\omega_{ij}=0\\
2\gamma'_{ij}\epsilon_i +2\sum_{p,q}\left(\gamma'_{pq}+\lambda_{pq}\right)[2(pq|ij)-(pj|iq)]+2\sum_{a,k,b}\Gamma'_{jakb}[(ik|ab)(\alpha\sigma'|\sigma\sigma'')-(ib|ak)(\alpha\sigma''|\sigma\sigma')]+2\omega_{ij}=0\\
2\gamma'_{ij}\epsilon_i +2\sum_{p,q}\left(\gamma'_{pq}+\lambda_{pq}\right)[2(pq|ij)-(pj|iq)]-2\sum_{a,k,b}x_{jb}x_{ka}[(ik|ab)-2(ib|ak)]+2\omega_{ij}=0\\
\gamma'_{ij}\epsilon_i +\sum_{p,q}\left(\gamma'_{pq}+\lambda_{pq}\right)[2(pq|ij)-(pj|iq)]+\sum_{a,k,b}x_{jb}x_{ka}[2(ib|ak)-(ik|ab)]+\omega_{ij}=0\\
\gamma'_{ij}\epsilon_i +\sum_{\mu,\nu,\theta,\varphi}\sum_{p,q}C_{\mu p}C_{\nu q}C_{\theta i}C_{\varphi j}\left(\gamma'_{pq}+\lambda_{pq}\right)[2(\mu\nu|\theta\varphi)-(\mu\varphi|\theta\nu)]+\sum_{a,k,b}x_{jb}x_{ka}[2(ib|ak)-(ik|ab)]+\omega_{ij}=0\\
\gamma'_{ij}\epsilon_i +\sum_{\theta,\varphi}C_{\theta i}C_{\varphi j}\sum_{\mu,\nu}\left(\gamma'_{\mu\nu}+\lambda_{\mu\nu}\right)[2(\mu\nu|\theta\varphi)-(\mu\varphi|\theta\nu)]+\sum_{\mu,\nu,\theta,\varphi}\sum_{a,k,b}C_{\mu i}C_{\nu k}C_{\theta a}C_{\varphi b}x_{jb}x_{ka}[2(\mu\varphi|\theta\nu)-(\mu\nu|\theta\varphi)]+\omega_{ij}=0\\
\gamma'_{ij}\epsilon_i +\sum_{\theta,\varphi}C_{\theta i}C_{\varphi j}\sum_{\mu,\nu}\left(\gamma'_{\mu\nu}+\lambda_{\mu\nu}\right)[2(\mu\nu|\theta\varphi)-(\mu\varphi|\theta\nu)]+\sum_{\mu}C_{\mu i}\sum_{\nu,\theta,\varphi}x_{j\varphi}x_{\nu\theta}[2(\mu\varphi|\theta\nu)-(\mu\nu|\theta\varphi)]+\omega_{ij}=0\\
\gamma'_{ij}\epsilon_i +\sum_{\theta,\varphi}C_{\theta i}C_{\varphi j}\sum_{\mu,\nu}\left(\gamma'_{\mu\nu}+\lambda_{\mu\nu}\right)[2(\mu\nu|\theta\varphi)-(\mu\varphi|\theta\nu)]+\sum_{\mu}C_{\mu i}\sum_{\nu,\theta,\varphi,\rho,\zeta}C_{\zeta j}S_{\zeta\rho}x_{\rho\varphi}x_{\nu\theta}[2(\mu\varphi|\theta\nu)-(\mu\nu|\theta\varphi)]+\omega_{ij}=0\\
\gamma'_{ij}\epsilon_i +\sum_{\theta,\varphi}C_{\theta i}C_{\varphi j}\sum_{\mu,\nu}\left(\gamma'_{\mu\nu}+\lambda_{\mu\nu}\right)[2(\mu\nu|\theta\varphi)-(\mu\varphi|\theta\nu)]+\sum_{\mu,\zeta}C_{\mu i}C_{\zeta j}\sum_{\varphi,\rho}S_{\zeta\rho}x_{\rho\varphi}\sum_{\nu,\theta}[2(\mu\varphi|\theta\nu)-(\mu\nu|\theta\varphi)]x_{\nu\theta}+\omega_{ij}=0\\
\end{equation}

In [38]:
omega_OO = numpy.zeros((nocc,nocc))
omega_OO = -numpy.einsum('mi,mj->ij', mo_occ, 
                                 numpy.einsum('zj,mz->mj', mo_occ,  
                                              (numpy.einsum('zr,mr->mz', ovlp,
                                                            numpy.einsum('rp,mp->mr',
                                                                         tda_eig_vec_ao, 
                                                                         0.5*fock_RHS_all.alpha_to_numpy(1)
                                                                        )
                                                           )
                                              )
                                             )
                        )
omega_OO -= numpy.einsum('pi,pj->ij', mo_occ,
                    numpy.einsum('tj,pt->pj', mo_occ, 0.5*fock_RHS_all.alpha_to_numpy(0)))
omega_OO -= ( numpy.matmul(mo_occ.T, numpy.matmul(fock_lambda.alpha_to_numpy(0), mo_occ)) 
            + numpy.matmul(mo_occ.T, numpy.matmul(fock_lambda.alpha_to_numpy(0), mo_occ)).T 
            )

#print(numpy.matmul(mo_occ.T, numpy.matmul(fock_lambda.alpha_to_numpy(0), mo_occ)))
# print("MO occupied energies:")
#print(eocc)
# print()
#eov = -evir + eocc.reshape(-1, 1)
#omega_OO-=eocc*0.5*vlx_dm_oo[i,:]
for i in range(nocc):
    omega_OO[i,:]-=eocc[i]*0.5*vlx_dm_oo[i,:]
    omega_OO[i,i]-=eocc[i]
print(omega_OO)

[[ 2.0767656e+01 -7.3624629e-03  6.4301225e-14 -5.5673204e-03
   1.1654229e-09]
 [-7.3624629e-03  1.5044790e+00 -1.9048292e-14 -2.7917346e-02
   1.5191025e-09]
 [ 6.4300684e-14 -1.9047420e-14  8.5213006e-01  1.8262343e-15
  -8.6661233e-10]
 [-5.5673204e-03 -2.7917346e-02  1.8111091e-15  7.3661966e-01
   6.5951504e-11]
 [-5.6750369e-11  4.5665708e-10 -6.0345565e-10  8.3050140e-11
   3.0565955e-01]]


### $\boldsymbol{\omega}$ entirely in AO basis

In [39]:
#epsilon_gamma_vv_ao is epsilon_a*dm_vv transformd to AO
epsilon_gamma_vv = -numpy.einsum("a,ab->ab", evir, 0.5*vlx_dm_vv)
epsilon_gamma_oo = -numpy.einsum("i,ij->ij", eocc, 0.5*vlx_dm_oo)-numpy.diag(eocc)
epsilon_lambda_ov = -numpy.einsum("i,ia->ia", eocc, lambda_OV)

#Components:
epsilon_gamma_vv_ao = numpy.matmul(mo_vir, numpy.matmul(epsilon_gamma_vv, mo_vir.T))
epsilon_gamma_oo_ao = numpy.matmul(mo_occ, numpy.matmul(epsilon_gamma_oo, mo_occ.T))
epsilon_gamma_ov_ao = numpy.matmul(mo_occ, numpy.matmul(epsilon_lambda_ov, mo_vir.T))

#Total:
epsilon_gamma_ao = (numpy.matmul(mo_vir, numpy.matmul(epsilon_gamma_vv, mo_vir.T))
                    +numpy.matmul(mo_occ, numpy.matmul(epsilon_gamma_oo, mo_occ.T))
                    +numpy.matmul(mo_occ, numpy.matmul(epsilon_lambda_ov, mo_vir.T))
                    +numpy.matmul(mo_vir, numpy.matmul(epsilon_lambda_ov.T, mo_occ.T))
                   )


#print(epsilon_gamma_vv_ao)

F = (numpy.einsum('zr,tz->tr', ovlp,
                  numpy.einsum('nz,tn->tz',tda_eig_vec_ao, 
                               0.5*fock_RHS_all.alpha_to_numpy(1).T
                              )
                 )
    )

Foo = numpy.einsum('zr,mr->mz', ovlp,
                   numpy.einsum('rp,mp->mr', tda_eig_vec_ao, 
                                 0.5*fock_RHS_all.alpha_to_numpy(1)
                                )
                    )
                                              

#c_ct_Fx_c_t = C C.transpose Fx C C.transpose, with Fx the 2PDM term in AO basis
vv_c_ct_Fx_c_ct = -numpy.matmul(mo_vir,
                            numpy.matmul(mo_vir.T, 
                                        numpy.matmul(F,
                                                    numpy.matmul(mo_vir,mo_vir.T)
                                                    )
                                        )
                           )

ov_c_ct_Fx_c_ct =  -numpy.matmul(mo_occ,
                            numpy.matmul(mo_occ.T, 
                                        numpy.matmul(F,
                                                    numpy.matmul(mo_vir,mo_vir.T)
                                                    )
                                        )
                           )


oo_c_ct_Fx_c_ct =  -numpy.matmul(mo_occ,
                            numpy.matmul(mo_occ.T, 
                                        numpy.matmul(F,
                                                    numpy.matmul(mo_occ,mo_occ.T)
                                                    )
                                        )
                           )

new_oo_c_ct_Fx_c_ct =  -numpy.matmul(mo_occ,
                            numpy.matmul(mo_occ.T, 
                                        numpy.matmul(Foo,
                                                    numpy.matmul(mo_occ,mo_occ.T)
                                                    )
                                        )
                           )

oo_c_ct_F1pdm_c_ct = -(numpy.matmul(mo_occ,
                            numpy.matmul(mo_occ.T, 
                                        numpy.matmul((fock_lambda.alpha_to_numpy(0)
                                                      +fock_lambda.alpha_to_numpy(0).T
                                                      +0.5*fock_RHS_all.alpha_to_numpy(0)),
                                                    numpy.matmul(mo_occ,mo_occ.T)
                                                    )
                                        )
                           )
                      )


c_ct_Fx_c_ct = (-numpy.matmul(mo_occ,
                            numpy.matmul(mo_occ.T, 
                                        numpy.matmul(Foo,
                                                    numpy.matmul(mo_occ,mo_occ.T)
                                                    )
                                        )
                           )
                 -numpy.matmul(mo_occ,
                            numpy.matmul(mo_occ.T, 
                                        numpy.matmul(F,
                                                    numpy.matmul(mo_vir,mo_vir.T)
                                                    )
                                        )
                           )
                 -numpy.matmul(mo_occ,
                            numpy.matmul(mo_occ.T, 
                                        numpy.matmul(F,
                                                    numpy.matmul(mo_vir,mo_vir.T)
                                                    )
                                        )
                           ).T
                -numpy.matmul(mo_vir,
                            numpy.matmul(mo_vir.T, 
                                        numpy.matmul(F,
                                                    numpy.matmul(mo_vir,mo_vir.T)
                                                    )
                                        )
                           )
            )
#c_ct_Fx_c_ct = (oo_c_ct_Fx_c_ct+vv_c_ct_Fx_c_ct+ov_c_ct_Fx_c_ct+ov_c_ct_Fx_c_ct.T)

iulia_omega_VV_ao = epsilon_gamma_vv_ao + vv_c_ct_Fx_c_ct
iulia_omega_OV_ao = epsilon_gamma_ov_ao + + ov_c_ct_Fx_c_ct + epsilon_gamma_ov_ao.T + ov_c_ct_Fx_c_ct.T
iulia_omega_OO_ao = epsilon_gamma_oo_ao + oo_c_ct_F1pdm_c_ct + new_oo_c_ct_Fx_c_ct 

iulia_omega_ao_full = epsilon_gamma_ao + oo_c_ct_F1pdm_c_ct + c_ct_Fx_c_ct 
sum_full = iulia_omega_VV_ao + iulia_omega_OV_ao + iulia_omega_OO_ao

print("\nomega VV in AO basis:\n")
print(iulia_omega_VV_ao)

print("\nomega OV in AO basis:\n")
print(iulia_omega_OV_ao)

print("\nomega OO in AO basis:\n")
print(iulia_omega_OO_ao)

print("\nFull omega in AO basis:\n")
print(iulia_omega_ao_full)


print("\nSum of components in AO basis:\n")
print(sum_full)


print("\nold:\n", F)
print("\nnew:\n", Foo)



omega VV in AO basis:

[[ 6.2204676e-04 -1.4335904e-03 -7.0313170e-03  7.1815046e-04
   6.1887557e-03  7.1815046e-04  6.1887557e-03 -1.4181374e-16
  -2.0874539e-16 -2.2253946e-03 -2.5284252e-03 -2.7102787e-12
   2.9241151e-12]
 [-1.4335904e-03  3.3039018e-03  1.6204615e-02 -1.6550743e-03
  -1.4262820e-02 -1.6550743e-03 -1.4262820e-02  3.7387864e-16
   3.5092805e-16  5.1287210e-03  5.8270957e-03  4.3072990e-12
  -4.6471377e-12]
 [-7.0313170e-03  1.6204615e-02  7.9478620e-02 -8.1176269e-03
  -6.9954714e-02 -8.1176269e-03 -6.9954714e-02  1.4879212e-15
   2.6837549e-15  2.5154789e-02  2.8580100e-02  3.3635216e-11
  -3.6288979e-11]
 [ 7.1815046e-04 -1.6550743e-03 -8.1176269e-03  8.2910179e-04
   7.1448934e-03  8.2910179e-04  7.1448934e-03 -1.7390275e-16
  -2.1162636e-16 -2.5692090e-03 -2.9190566e-03 -3.7618987e-12
   4.0587062e-12]
 [ 6.1887557e-03 -1.4262820e-02 -6.9954714e-02  7.1448934e-03
   6.1572055e-02  7.1448934e-03  6.1572055e-02 -1.3298758e-15
  -2.3346549e-15 -2.2140495e-02 -2.5

In [40]:
omega_VV_ao = -(numpy.einsum('zr,tz->tr', ovlp,
                         numpy.einsum('nz,tn->tz',
                                   tda_eig_vec_ao, 
                                    0.5*fock_RHS_all.alpha_to_numpy(1).T
                                                                        )
                                                           )
                                              )

# maybe one has to skip teh overlap matrix here already? since one does not transform to MO at all...
omega_VV_ao_wo_s = - (numpy.einsum('nz,tn->tz', tda_eig_vec_ao, 0.5*fock_RHS_all.alpha_to_numpy(1).T))

omega_OV_ao = -(numpy.einsum('rz,mr->mz', ovlp,
                         numpy.einsum('tr,mt->mr',
                               tda_eig_vec_ao, 
                                      0.5*fock_RHS_all.alpha_to_numpy(1).T
                                                                        )
                                                           )
                                              )

omega_OO_ao = -(numpy.einsum('zr,mr->mz', ovlp,
                          numpy.einsum('rp,mp->mr',
                                    tda_eig_vec_ao, 
                                            0.5*fock_RHS_all.alpha_to_numpy(1)
                                                                        )
                                                           )
                                              )
omega_OO_ao -= 0.5*fock_RHS_all.alpha_to_numpy(0)
omega_OO_ao -= ( fock_lambda.alpha_to_numpy(0) + fock_lambda.alpha_to_numpy(0).T )

# Add the "diagonal" parts, transformed to AO
omega_VV_ao -= numpy.matmul(mo_vir, numpy.matmul(ovlp,
                                                 numpy.matmul(numpy.einsum('a,ab->ab', evir, 0.5*vlx_dm_vv),
                                                              numpy.matmul(ovlp, mo_vir).T).T).T)

omega_VV_ao_wo_s -= numpy.matmul(mo_vir, numpy.matmul(numpy.einsum('a,ab->ab', evir, 0.5*vlx_dm_vv), mo_vir.T))

omega_OO_ao -= numpy.matmul(mo_occ, numpy.matmul(numpy.diag(eocc) + numpy.einsum('i,ij->ij', eocc, 0.5*vlx_dm_oo), mo_occ.T))
omega_OV_ao -= (numpy.matmul(mo_occ, numpy.matmul(numpy.einsum('i,ia->ia', eocc, lambda_OV), mo_vir.T))
            + numpy.matmul(mo_vir, numpy.matmul(numpy.einsum('i,ia->ia', eocc, lambda_OV).T, mo_occ.T))
            )


In [41]:
# Transform those calculated entirely in MO to the AO basis
omega_VV_ao2 = numpy.matmul(mo_vir, numpy.matmul(omega_VV, mo_vir.T))
#omega_VV_wo_e_ao = numpy.matmul(mo_vir, numpy.matmul(omega_VV_wo_e, mo_vir.T))
omega_OV_ao2 = (numpy.matmul(mo_occ, numpy.matmul(omega_OV, mo_vir.T)))
                #+ numpy.matmul(mo_vir, numpy.matmul(omega_OV.T, mo_occ.T)))
omega_OV_ao2 += omega_OV_ao2.T
omega_OO_ao2 = numpy.matmul(mo_occ, numpy.matmul(omega_OO, mo_occ.T))

In [42]:
print("omega_VV_ao2:")
print(omega_VV_ao2)
print("\niulia_omega_VV:\n", iulia_omega_VV_ao)
print("\nomega_VV_ao_wo_s:")
print(omega_VV_ao_wo_s)
print("\nomega_VV_ao:")
print(omega_VV_ao)
print()
#print("omega_VV_wo_e_ao:")
#print(omega_VV_wo_e_ao)
#print("\nomega_VV_ao_wo_e")
#print(omega_VV_ao_wo_e)

omega_VV_ao2:
[[ 6.2204676e-04 -1.4335904e-03 -7.0313170e-03  7.1815046e-04
   6.1887557e-03  7.1815046e-04  6.1887557e-03 -1.3998924e-16
  -2.1235391e-16 -2.2253946e-03 -2.5284252e-03 -2.7102787e-12
   2.9241151e-12]
 [-1.4335904e-03  3.3039018e-03  1.6204615e-02 -1.6550743e-03
  -1.4262820e-02 -1.6550743e-03 -1.4262820e-02  3.5259261e-16
   3.9386202e-16  5.1287210e-03  5.8270957e-03  4.3072990e-12
  -4.6471377e-12]
 [-7.0313170e-03  1.6204615e-02  7.9478620e-02 -8.1176269e-03
  -6.9954714e-02 -8.1176269e-03 -6.9954714e-02  1.5124418e-15
   2.6347150e-15  2.5154789e-02  2.8580100e-02  3.3635216e-11
  -3.6288979e-11]
 [ 7.1815046e-04 -1.6550743e-03 -8.1176269e-03  8.2910179e-04
   7.1448934e-03  8.2910179e-04  7.1448934e-03 -1.6081781e-16
  -2.3366953e-16 -2.5692090e-03 -2.9190566e-03 -3.7618987e-12
   4.0587062e-12]
 [ 6.1887557e-03 -1.4262820e-02 -6.9954714e-02  7.1448934e-03
   6.1572055e-02  7.1448934e-03  6.1572055e-02 -1.3450104e-15
  -2.3076774e-15 -2.2140495e-02 -2.5155353e-02

In [43]:
print("omega_OO_ao2:")
print(omega_OO_ao2)

print("\niulia_omega_OO in AO:")
print(iulia_omega_OO_ao)
print("\nomegaOV_ao2:")
print(omega_OV_ao2)
print("\niulia_omega_OV:\n", iulia_omega_OV_ao)
print("\nTOTAL:")
print(omega_OV_ao2+omega_OO_ao2+omega_VV_ao2)

print("\nOmega from tdaorbitalresponse.compute_omega:\n", orb_resp.omega_ao)


omega_OO_ao2:
[[ 2.0667551e+01  2.9155433e-01 -3.4161102e-01 -3.7283887e-02
   4.9366660e-02 -3.7283887e-02  4.9366660e-02  3.4409584e-14
   2.0103839e-14  3.7423790e-02 -3.7474741e-02  5.4127781e-10
   4.3021738e-10]
 [ 2.9155433e-01  3.6922043e-01  3.7777133e-01  8.1132499e-02
  -1.6877492e-02  8.1132499e-02 -1.6877492e-02 -3.8296533e-15
  -1.3241788e-15  2.0907856e-03 -1.7664185e-02  4.6514264e-10
   3.6970374e-10]
 [-3.4161102e-01  3.7777133e-01  4.1774949e-01  6.8740603e-02
  -2.5606110e-02  6.8740603e-02 -2.5606110e-02 -6.1728548e-15
  -2.4891646e-15 -5.0883674e-02 -5.4182465e-02  4.4124756e-10
   3.5071147e-10]
 [-3.7283887e-02  8.1132499e-02  6.8740603e-02  1.0587692e-01
   3.3454515e-02 -1.4840151e-02 -2.1623014e-02  1.1534920e-01
   6.0147509e-02  8.1175039e-02  5.3661140e-02 -1.1008298e-12
  -8.7491979e-13]
 [ 4.9366660e-02 -1.6877492e-02 -2.5606110e-02  3.3454515e-02
   1.7159155e-02 -2.1623014e-02 -7.9701348e-03  5.2628420e-02
   2.7442483e-02  2.9575202e-02  2.1720680e-02

   7.9221138e-02]]
