In [1]:
import veloxchem as vlx

In [2]:
class MockTask:
    def __init__(self, mol, basis, comm, ostream):

        self.molecule = mol
        self.ao_basis = basis
        self.mpi_comm = comm
        self.ostream = ostream

In [3]:
import adcc
from mpi4py import MPI
import sys
import numpy
numpy.set_printoptions(precision=7, suppress=True)

In [37]:
# Input settings
#molecule_string = """
#    O 0 0 0
#    H 0 0 1.795239827225189
#    H 1.693194615993441 0 -0.599043184453037"""

molecule_string = """
    H 0 0 0
    H 0 0 1.795239827225189
    """

basis_set_label = '6-31G'
scf_settings = {'conv_thresh': 1.0e-6}
method_settings = {} #{'xcfun': 'b3lyp', 'grid_level': 4}
rsp_settings = {'conv_thresh': 1.0e-4, 'nstates': 1}

In [38]:
# Communicator and output stream
comm = MPI.COMM_WORLD
ostream = vlx.OutputStream(sys.stdout)

In [39]:
# Molecule and basis set
molecule = vlx.Molecule.read_str(molecule_string, units='au')
basis = vlx.MolecularBasis.read(molecule, basis_set_label)

ostream.print_block(molecule.get_string())
ostream.print_block(basis.get_string('Atomic Basis', molecule))
ostream.flush()

                                              Molecular Geometry (Angstroms)                                              
                                                                                                                          
                          Atom         Coordinate X          Coordinate Y          Coordinate Z                           
                                                                                                                          
                           H           0.000000000000        0.000000000000        0.000000000000                         
                           H           0.000000000000        0.000000000000        0.950000004704                         
                                                                                                                          
                                              Molecular Basis (Atomic Basis)                                              
                

In [40]:
# SCF
task = MockTask(molecule, basis, comm, ostream)
scfdrv = vlx.ScfRestrictedDriver(comm, ostream)
scfdrv.update_settings(scf_settings, method_settings)
scfdrv.compute(molecule, basis)
scfdrv.task = task

                                                                                                                          
                                            Self Consistent Field Driver Setup                                            
                                                                                                                          
                   Wave Function Model             : Spin-Restricted Hartree-Fock                                         
                   Initial Guess Model             : Superposition of Atomic Densities                                    
                   Convergence Accelerator         : Two Level Direct Inversion of Iterative Subspace                     
                   Max. Number of Iterations       : 50                                                                   
                   Max. Number of Error Vectors    : 10                                                                   
                

In [41]:
# SCF first-order properties
scf_prop = vlx.ScfFirstOrderProperties(comm, ostream)
scf_prop.compute(molecule, basis, scfdrv.scf_tensors)
scf_prop.print_properties(molecule)

                                                                                                                          
                                                Ground-State Dipole Moment                                                
                                               ----------------------------                                               
                                                                                                                          
                                   X   :         0.000000 a.u.         0.000000 Debye                                     
                                   Y   :         0.000000 a.u.         0.000000 Debye                                     
                                   Z   :        -0.000000 a.u.        -0.000000 Debye                                     
                                 Total :         0.000000 a.u.         0.000000 Debye                                     
                

In [42]:
# Linear Response
#lr_eig_drv = vlx.LinearResponseEigenSolver(comm, ostream)
#lr_eig_drv.update_settings(rsp_settings, method_settings)
#lr_results = lr_eig_drv.compute(molecule, basis, scfdrv.scf_tensors)
#lr_eig_drv.ostream.flush()

In [43]:
# TDHF/TDA, i.e. CIS
tda_drv = vlx.TDAExciDriver(comm, ostream)
tda_drv.update_settings(rsp_settings, method_settings)
tda_results = tda_drv.compute(molecule, basis, scfdrv.scf_tensors)
tda_drv.ostream.flush()

                                                                                                                          
                                                     TDA Driver Setup                                                     
                                                                                                                          
                               Number of States                : 1                                                        
                               Max. Number of Iterations       : 150                                                      
                               Convergence Threshold           : 1.0e-04                                                  
                               ERI Screening Scheme            : Cauchy Schwarz + Density                                 
                               ERI Screening Threshold         : 1.0e-15                                                  
                

In [44]:
# Get eigenvalues and eigenvectors

nocc = molecule.number_of_alpha_electrons()
mo = scfdrv.scf_tensors['C'] # MO coefficients
mo_occ = mo[:, :nocc]        # occupied
mo_vir = mo[:, nocc:]        # virtual

nocc = mo_occ.shape[1]
nvir = mo_vir.shape[1]

#eig_vals = lr_results["eigenvalues"]
#eig_vecs = lr_results["eigenvectors"]

#eig_vec = eig_vecs[:, 0].copy() # first eigenvector
#print(eig_vec)

In [45]:
# Convert the first eigenvector to matrix form
#eig_vec_as_mat = vlx.LinearResponseEigenSolver.lrvec2mat(eig_vec, nocc, nocc + nvir)

In [46]:
tda_eig_vals = tda_results["eigenvalues"]
tda_eig_vecs = tda_results["eigenvectors"]
tda_size = tda_eig_vecs[:,0].shape
tda_eig_vec=tda_eig_vecs[:,0].copy()
tda_eig_vec_as_mat = tda_eig_vec.reshape(nocc, nvir) #/ numpy.sqrt(2.0)

In [47]:
print(tda_eig_vec)

[-0.9996748  0.        -0.0255009]


In [48]:
#tda_eig_vec_as_mat = vlx.LinearResponseEigenSolver.lrvec2mat(tda_eig_vec, nocc, nocc + nvir)

In [49]:
print(tda_eig_vec_as_mat)

[[-0.9996748  0.        -0.0255009]]


In [50]:
adc1 = adcc.run_adc(scfdrv, method='adc1', n_singlets=1, conv_tol=1e-4)

Starting adc1 singlet Jacobi-Davidson ...
Niter n_ss  max_residual  time  Ritz values
  1     3    1.3509e-32   64ms  [0.4843494]
=== Converged ===
    Number of matrix applies:    3
    Total solver time:           65.554ms


In [51]:
adc1_eig_vec = adc1.excitation_vector[0]["s"].to_ndarray()
adc1_eig_vals = adc1.excitation_energy

In [52]:
print(adc1_eig_vec)
print(adc1_eig_vals)
print(adc1.describe())

[[ 0.7068768 -0.         0.0180318  0.         0.         0.       ]
 [ 0.         0.         0.         0.7068768 -0.         0.0180318]]
[0.4843494]
+----------------------------------------------------+
| adc1                          singlet ,  converged |
+----------------------------------------------------+
|  #        excitation energy     osc str    |v1|^2  |
|          (au)           (eV)                       |
|  0     0.4843494      13.17982   0.7768         1  |
+----------------------------------------------------+



In [53]:
print(tda_eig_vecs[:,0])
print(tda_eig_vals)

[-0.9996748  0.        -0.0255009]
[0.4843494]


In [54]:
numpy.linalg.norm(adc1_eig_vec)

1.0

In [55]:
0.9999995/numpy.sqrt(2.0)

0.7071064276331569

In [56]:
0.0009539/numpy.sqrt(2.0)

0.0006745091585738476

In [57]:
adc1_eig_vec

array([[ 0.7068768, -0.       ,  0.0180318,  0.       ,  0.       ,
         0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.7068768, -0.       ,
         0.0180318]])

In [58]:
vlx_dm_oo = -numpy.einsum('ia,ja->ij', tda_eig_vec_as_mat, tda_eig_vec_as_mat)
vlx_dm_vv = numpy.einsum('ia,ib->ab', tda_eig_vec_as_mat, tda_eig_vec_as_mat)
vlx_DM_ovov = -numpy.einsum('ib,ja->iajb', tda_eig_vec_as_mat, tda_eig_vec_as_mat)

In [67]:
adcc_dm_oo = -numpy.einsum('ia,ja->ij', adc1_eig_vec, adc1_eig_vec)
adcc_dm_vv = numpy.einsum('ia,ib->ab', adc1_eig_vec, adc1_eig_vec)
adcc_DM_ovov = -numpy.einsum('ib,ja->iajb', adc1_eig_vec, adc1_eig_vec)

foo = adc1.reference_state.fock("o1o1").to_ndarray()
fvv = adc1.reference_state.fock("v1v1").to_ndarray()
ovov = adc1.reference_state.eri("o1v1o1v1").to_ndarray()

excitation_energy = (numpy.einsum('ij,ij->',adcc_dm_oo,foo)
                     + numpy.einsum('ab,ab->', adcc_dm_vv, fvv)
                     + numpy.einsum('iajb,iajb->', adcc_DM_ovov, ovov)
                    )

In [68]:
print(excitation_energy)

0.48434940135740473


In [95]:
vlx_excitation_energy = (2.0*numpy.einsum('ij,ij->', vlx_dm_oo,foo[:nocc,:nocc])
                        +2.0*numpy.einsum('ab,ab->', vlx_dm_vv, fvv[:nvir,:nvir])
                        +2.0*numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc, :nvir, :nocc, :nvir])
                        +numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc, nvir:, :nocc, nvir:])
                        +numpy.einsum('iajb,iajb->', vlx_DM_ovov, ovov[:nocc,nvir:,nocc:,:nvir])
                        )

In [96]:
print(vlx_excitation_energy)

0.43854701612255836


In [71]:
print(ovov)

[[[[ 0.3374075 -0.        -0.0581306  0.         0.         0.       ]
   [ 0.         0.         0.         0.         0.         0.       ]]

  [[-0.         0.4120629 -0.         0.         0.         0.       ]
   [ 0.         0.         0.         0.         0.         0.       ]]

  [[-0.0581306 -0.         0.4708726  0.         0.         0.       ]
   [ 0.         0.         0.         0.         0.         0.       ]]

  [[ 0.         0.         0.         0.4393378 -0.        -0.139109 ]
   [-0.1019303  0.         0.0809784  0.         0.         0.       ]]

  [[ 0.         0.         0.        -0.         0.5094985  0.       ]
   [ 0.        -0.0974356 -0.         0.         0.         0.       ]]

  [[ 0.         0.         0.        -0.139109  -0.         0.586764 ]
   [ 0.0809784 -0.        -0.1158914  0.         0.         0.       ]]]


 [[[ 0.         0.         0.        -0.1019303  0.         0.0809784]
   [ 0.4393378 -0.        -0.139109   0.         0.         0. 

In [89]:
print(vlx_DM_ovov)
print()
#print(adcc_DM_ovov)

[[[[-0.9993497  0.        -0.0254926]]

  [[ 0.        -0.         0.       ]]

  [[-0.0254926  0.        -0.0006503]]]]



In [90]:
print(adcc_DM_ovov)

[[[[-0.4996749  0.        -0.0127463 -0.        -0.        -0.       ]
   [-0.        -0.        -0.        -0.        -0.        -0.       ]]

  [[ 0.        -0.         0.        -0.        -0.        -0.       ]
   [-0.        -0.        -0.        -0.        -0.        -0.       ]]

  [[-0.0127463  0.        -0.0003251 -0.        -0.        -0.       ]
   [-0.        -0.        -0.        -0.        -0.        -0.       ]]

  [[-0.        -0.        -0.        -0.        -0.        -0.       ]
   [-0.4996749  0.        -0.0127463 -0.        -0.        -0.       ]]

  [[-0.        -0.        -0.        -0.        -0.        -0.       ]
   [ 0.        -0.         0.        -0.        -0.        -0.       ]]

  [[-0.        -0.        -0.        -0.        -0.        -0.       ]
   [-0.0127463  0.        -0.0003251 -0.        -0.        -0.       ]]]


 [[[-0.        -0.        -0.        -0.4996749  0.        -0.0127463]
   [-0.        -0.        -0.        -0.        -0.        -0. 